let infoRotas = {
"rotas":[
{"rota": "Maceió - Barra De Santo Antônio", "pe": 3},
{"rota": "Maceió - Barra De São Miguel", "pe": 3},
{"rota": "Maceió - Coqueiro Seco", "pe": 3},
{"rota": "Maceió - Maceió", "pe": 1},
{"rota": "Maceió - Marechal Deodoro", "pe": 1},
{"rota": "Maceió - Messias", "pe": 3},
{"rota": "Maceió - Murici", "pe": 3},
{"rota": "Maceió - Paripueira", "pe": 2},
{"rota": "Maceió - Pilar", "pe": 3},
{"rota": "Maceió - Rio Largo", "pe": 3},
{"rota": "Maceió - Santa Luzia Do Norte", "pe": 3},
{"rota": "Maceió - Satuba", "pe": 3},
{"rota": "Feira de Santana - Abaíra", "pe": 5},
{"rota": "Feira de Santana - Abaré", "pe": 5},
{"rota": "Feira de Santana - Acajutiba", "pe": 2},
{"rota": "Feira de Santana - Adustina", "pe": 3},
{"rota": "Feira de Santana - Água Fria", "pe": 2},
{"rota": "Feira de Santana - Alagoinhas", "pe": 2},
{"rota": "Feira de Santana - Amargosa", "pe": 3},
{"rota": "Feira de Santana - Amélia Rodrigues", "pe": 2},
{"rota": "Feira de Santana - América Dourada", "pe": 2},
{"rota": "Feira de Santana - Andaraí", "pe": 5},
{"rota": "Feira de Santana - Andorinha", "pe": 3},
{"rota": "Feira de Santana - Angical", "pe": 3},
{"rota": "Feira de Santana - Anguera", "pe": 3},
{"rota": "Feira de Santana - Antas", "pe": 3},
{"rota": "Feira de Santana - Antônio Cardoso", "pe": 3},
{"rota": "Feira de Santana - Antônio Gonçalves", "pe": 2},
{"rota": "Feira de Santana - Aporá", "pe": 2},
{"rota": "Feira de Santana - Araçás", "pe": 2},
{"rota": "Feira de Santana - Araci", "pe": 3},
{"rota": "Feira de Santana - Aramari", "pe": 2},
{"rota": "Feira de Santana - Aratuípe", "pe": 2},
{"rota": "Feira de Santana - Baianópolis", "pe": 5},
{"rota": "Feira de Santana - Baixa Grande", "pe": 3},
{"rota": "Feira de Santana - Banzaê", "pe": 3},
{"rota": "Feira de Santana - Barra", "pe": 2},
{"rota": "Feira de Santana - Barra Do Mendes", "pe": 3},
{"rota": "Feira de Santana - Barreiras", "pe": 3},
{"rota": "Feira de Santana - Barro Alto", "pe": 5},
{"rota": "Feira de Santana - Barrocas", "pe": 2},
{"rota": "Feira de Santana - Biritinga", "pe": 2},
{"rota": "Feira de Santana - Boa Vista Do Tupim", "pe": 5},
{"rota": "Feira de Santana - Boninal", "pe": 2},
{"rota": "Feira de Santana - Bonito", "pe": 2},
{"rota": "Feira de Santana - Brejões", "pe": 3},
{"rota": "Feira de Santana - Brotas De Macaúbas", "pe": 2},
{"rota": "Feira de Santana - Buritirama", "pe": 2},
{"rota": "Feira de Santana - Cabaceiras Do Paraguaçu", "pe": 3},
{"rota": "Feira de Santana - Cachoeira", "pe": 2},
{"rota": "Feira de Santana - Caém", "pe": 2},
{"rota": "Feira de Santana - Cafarnaum", "pe": 2},
{"rota": "Feira de Santana - Cairu", "pe": 5},
{"rota": "Feira de Santana - Caldeirão Grande", "pe": 2},
{"rota": "Feira de Santana - Camamu", "pe": 2},
{"rota": "Feira de Santana - Campo Alegre De Lourdes", "pe": 3},
{"rota": "Feira de Santana - Campo Formoso", "pe": 3},
{"rota": "Feira de Santana - Canarana", "pe": 2},
{"rota": "Feira de Santana - Candeal", "pe": 2},
{"rota": "Feira de Santana - Cansanção", "pe": 3},
{"rota": "Feira de Santana - Canudos", "pe": 5},
{"rota": "Feira de Santana - Capela Do Alto Alegre", "pe": 2},
{"rota": "Feira de Santana - Capim Grosso", "pe": 2},
{"rota": "Feira de Santana - Cardeal Da Silva", "pe": 3},
{"rota": "Feira de Santana - Casa Nova", "pe": 3},
{"rota": "Feira de Santana - Castro Alves", "pe": 3},
{"rota": "Feira de Santana - Catolândia", "pe": 3},
{"rota": "Feira de Santana - Catu", "pe": 2},
{"rota": "Feira de Santana - Central", "pe": 2},
{"rota": "Feira de Santana - Chorrochó", "pe": 5},
{"rota": "Feira de Santana - Cícero Dantas", "pe": 4},
{"rota": "Feira de Santana - Cipó", "pe": 2},
{"rota": "Feira de Santana - Conceição Da Feira", "pe": 2},
{"rota": "Feira de Santana - Conceição Do Almeida", "pe": 2},
{"rota": "Feira de Santana - Conceição Do Coité", "pe": 2},
{"rota": "Feira de Santana - Conceição Do Jacuípe", "pe": 2},
{"rota": "Feira de Santana - Conde", "pe": 2},
{"rota": "Feira de Santana - Coração De Maria", "pe": 2},
{"rota": "Feira de Santana - Coronel João Sá", "pe": 5},
{"rota": "Feira de Santana - Cotegipe", "pe": 3},
{"rota": "Feira de Santana - Cravolândia", "pe": 2},
{"rota": "Feira de Santana - Crisópolis", "pe": 2},
{"rota": "Feira de Santana - Cristópolis", "pe": 3},
{"rota": "Feira de Santana - Cruz Das Almas", "pe": 2},
{"rota": "Feira de Santana - Curaçá", "pe": 3},
{"rota": "Feira de Santana - Dom Macedo Costa", "pe": 3},
{"rota": "Feira de Santana - Elísio Medrado", "pe": 3},
{"rota": "Feira de Santana - Entre Rios", "pe": 2},
{"rota": "Feira de Santana - Esplanada", "pe": 2},
{"rota": "Feira de Santana - Euclides Da Cunha", "pe": 3},
{"rota": "Feira de Santana - Fátima", "pe": 3},
{"rota": "Feira de Santana - Feira De Santana", "pe": 1},
{"rota": "Feira de Santana - Filadélfia", "pe": 2},
{"rota": "Feira de Santana - Formosa Do Rio Preto", "pe": 3},
{"rota": "Feira de Santana - Gandu", "pe": 2},
{"rota": "Feira de Santana - Gavião", "pe": 2},
{"rota": "Feira de Santana - Gentio Do Ouro", "pe": 2},
{"rota": "Feira de Santana - Glória", "pe": 5},
{"rota": "Feira de Santana - Governador Mangabeira", "pe": 2},
{"rota": "Feira de Santana - Heliópolis", "pe": 3},
{"rota": "Feira de Santana - Iaçu", "pe": 3},
{"rota": "Feira de Santana - Ibipeba", "pe": 2},
{"rota": "Feira de Santana - Ibiquera", "pe": 3},
{"rota": "Feira de Santana - Ibitiara", "pe": 5},
{"rota": "Feira de Santana - Ibititá", "pe": 2},
{"rota": "Feira de Santana - Ibotirama", "pe": 3},
{"rota": "Feira de Santana - Ichu", "pe": 2},
{"rota": "Feira de Santana - Igrapiúna", "pe": 2},
{"rota": "Feira de Santana - Inhambupe", "pe": 2},
{"rota": "Feira de Santana - Ipecaetá", "pe": 3},
{"rota": "Feira de Santana - Ipirá", "pe": 3},
{"rota": "Feira de Santana - Ipupiara", "pe": 2},
{"rota": "Feira de Santana - Irajuba", "pe": 3},
{"rota": "Feira de Santana - Iraquara", "pe": 2},
{"rota": "Feira de Santana - Irará", "pe": 2},
{"rota": "Feira de Santana - Irecê", "pe": 2},
{"rota": "Feira de Santana - Itaberaba", "pe": 3},
{"rota": "Feira de Santana - Itaeté", "pe": 5},
{"rota": "Feira de Santana - Itaguaçu Da Bahia", "pe": 2},
{"rota": "Feira de Santana - Itanagra", "pe": 2},
{"rota": "Feira de Santana - Itaparica", "pe": 5},
{"rota": "Feira de Santana - Itapicuru", "pe": 2},
{"rota": "Feira de Santana - Itaquara", "pe": 3},
{"rota": "Feira de Santana - Itatim", "pe": 3},
{"rota": "Feira de Santana - Itiruçu", "pe": 3},
{"rota": "Feira de Santana - Itiúba", "pe": 2},
{"rota": "Feira de Santana - Ituberá", "pe": 2},
{"rota": "Feira de Santana - Jacobina", "pe": 2},
{"rota": "Feira de Santana - Jaguarari", "pe": 3},
{"rota": "Feira de Santana - Jaguaripe", "pe": 2},
{"rota": "Feira de Santana - Jandaíra", "pe": 2},
{"rota": "Feira de Santana - Jeremoabo", "pe": 3},
{"rota": "Feira de Santana - Jiquiriçá", "pe": 3},
{"rota": "Feira de Santana - João Dourado", "pe": 2},
{"rota": "Feira de Santana - Juazeiro", "pe": 3},
{"rota": "Feira de Santana - Jussara", "pe": 2},
{"rota": "Feira de Santana - Laje", "pe": 3},
{"rota": "Feira de Santana - Lajedinho", "pe": 3},
{"rota": "Feira de Santana - Lamarão", "pe": 2},
{"rota": "Feira de Santana - Lapão", "pe": 2},
{"rota": "Feira de Santana - Lençóis", "pe": 2},
{"rota": "Feira de Santana - Luís Eduardo Magalhães", "pe": 3},
{"rota": "Feira de Santana - Macajuba", "pe": 3},
{"rota": "Feira de Santana - Macururé", "pe": 5},
{"rota": "Feira de Santana - Mairi", "pe": 2},
{"rota": "Feira de Santana - Mansidão", "pe": 3},
{"rota": "Feira de Santana - Maragogipe", "pe": 2},
{"rota": "Feira de Santana - Marcionílio Souza", "pe": 3},
{"rota": "Feira de Santana - Miguel Calmon", "pe": 2},
{"rota": "Feira de Santana - Milagres", "pe": 3},
{"rota": "Feira de Santana - Mirangaba", "pe": 2},
{"rota": "Feira de Santana - Monte Santo", "pe": 3},
{"rota": "Feira de Santana - Morro Do Chapéu", "pe": 2},
{"rota": "Feira de Santana - Mucugê", "pe": 5},
{"rota": "Feira de Santana - Mulungu Do Morro", "pe": 2},
{"rota": "Feira de Santana - Mundo Novo", "pe": 3},
{"rota": "Feira de Santana - Muniz Ferreira", "pe": 2},
{"rota": "Feira de Santana - Muquém Do São Francisco", "pe": 3},
{"rota": "Feira de Santana - Muritiba", "pe": 2},
{"rota": "Feira de Santana - Mutuípe", "pe": 3},
{"rota": "Feira de Santana - Nazaré", "pe": 2},
{"rota": "Feira de Santana - Nilo Peçanha", "pe": 3},
{"rota": "Feira de Santana - Nordestina", "pe": 3},
{"rota": "Feira de Santana - Nova Fátima", "pe": 2},
{"rota": "Feira de Santana - Nova Ibiá", "pe": 5},
{"rota": "Feira de Santana - Nova Itarana", "pe": 5},
{"rota": "Feira de Santana - Nova Redenção", "pe": 5},
{"rota": "Feira de Santana - Nova Soure", "pe": 2},
{"rota": "Feira de Santana - Novo Horizonte", "pe": 2},
{"rota": "Feira de Santana - Novo Triunfo", "pe": 3},
{"rota": "Feira de Santana - Olindina", "pe": 2},
{"rota": "Feira de Santana - Oliveira Dos Brejinhos", "pe": 2},
{"rota": "Feira de Santana - Ouriçangas", "pe": 2},
{"rota": "Feira de Santana - Ourolândia", "pe": 2},
{"rota": "Feira de Santana - Palmeiras", "pe": 2},
{"rota": "Feira de Santana - Paripiranga", "pe": 3},
{"rota": "Feira de Santana - Paulo Afonso", "pe": 3},
{"rota": "Feira de Santana - Pé De Serra", "pe": 2},
{"rota": "Feira de Santana - Pedrão", "pe": 2},
{"rota": "Feira de Santana - Pedro Alexandre", "pe": 5},
{"rota": "Feira de Santana - Piatã", "pe": 2},
{"rota": "Feira de Santana - Pilão Arcado", "pe": 3},
{"rota": "Feira de Santana - Pindobaçu", "pe": 2},
{"rota": "Feira de Santana - Pintadas", "pe": 3},
{"rota": "Feira de Santana - Piraí Do Norte", "pe": 2},
{"rota": "Feira de Santana - Piritiba", "pe": 3},
{"rota": "Feira de Santana - Ponto Novo", "pe": 2},
{"rota": "Feira de Santana - Presidente Dutra", "pe": 2},
{"rota": "Feira de Santana - Presidente Tancredo Neves", "pe": 2},
{"rota": "Feira de Santana - Queimadas", "pe": 3},
{"rota": "Feira de Santana - Quijingue", "pe": 3},
{"rota": "Feira de Santana - Quixabeira", "pe": 2},
{"rota": "Feira de Santana - Rafael Jambeiro", "pe": 3},
{"rota": "Feira de Santana - Remanso", "pe": 5},
{"rota": "Feira de Santana - Retirolândia", "pe": 2},
{"rota": "Feira de Santana - Riachão Das Neves", "pe": 2},
{"rota": "Feira de Santana - Riachão Do Jacuípe", "pe": 2},
{"rota": "Feira de Santana - Ribeira Do Amparo", "pe": 2},
{"rota": "Feira de Santana - Ribeira Do Pombal", "pe": 3},
{"rota": "Feira de Santana - Rio Real", "pe": 2},
{"rota": "Feira de Santana - Rodelas", "pe": 5},
{"rota": "Feira de Santana - Ruy Barbosa", "pe": 3},
{"rota": "Feira de Santana - Salinas Da Margarida", "pe": 3},
{"rota": "Feira de Santana - Santa Bárbara", "pe": 2},
{"rota": "Feira de Santana - Santa Brígida", "pe": 3},
{"rota": "Feira de Santana - Santa Inês", "pe": 3},
{"rota": "Feira de Santana - Santa Rita De Cássia", "pe": 5},
{"rota": "Feira de Santana - Santa Terezinha", "pe": 3},
{"rota": "Feira de Santana - Santaluz", "pe": 2},
{"rota": "Feira de Santana - Santanópolis", "pe": 2},
{"rota": "Feira de Santana - Santo Amaro", "pe": 2},
{"rota": "Feira de Santana - Santo Antônio De Jesus", "pe": 2},
{"rota": "Feira de Santana - Santo Estêvão", "pe": 3},
{"rota": "Feira de Santana - São Desidério", "pe": 3},
{"rota": "Feira de Santana - São Domingos", "pe": 2},
{"rota": "Feira de Santana - São Felipe", "pe": 2},
{"rota": "Feira de Santana - São Félix", "pe": 2},
{"rota": "Feira de Santana - São Gabriel", "pe": 2},
{"rota": "Feira de Santana - São Gonçalo Dos Campos", "pe": 2},
{"rota": "Feira de Santana - São José Do Jacuípe", "pe": 2},
{"rota": "Feira de Santana - São Miguel Das Matas", "pe": 3},
{"rota": "Feira de Santana - Sapeaçu", "pe": 2},
{"rota": "Feira de Santana - Sátiro Dias", "pe": 2},
{"rota": "Feira de Santana - Saubara", "pe": 2},
{"rota": "Feira de Santana - Saúde", "pe": 2},
{"rota": "Feira de Santana - Seabra", "pe": 2},
{"rota": "Feira de Santana - Senhor Do Bonfim", "pe": 3},
{"rota": "Feira de Santana - Sento Sé", "pe": 3},
{"rota": "Feira de Santana - Serra Preta", "pe": 3},
{"rota": "Feira de Santana - Serrinha", "pe": 2},
{"rota": "Feira de Santana - Serrolândia", "pe": 2},
{"rota": "Feira de Santana - Sítio Do Quinto", "pe": 3},
{"rota": "Feira de Santana - Sobradinho", "pe": 3},
{"rota": "Feira de Santana - Souto Soares", "pe": 2},
{"rota": "Feira de Santana - Tanquinho", "pe": 2},
{"rota": "Feira de Santana - Taperoá", "pe": 2},
{"rota": "Feira de Santana - Tapiramutá", "pe": 3},
{"rota": "Feira de Santana - Teodoro Sampaio", "pe": 2},
{"rota": "Feira de Santana - Teofilândia", "pe": 3},
{"rota": "Feira de Santana - Teolândia", "pe": 2},
{"rota": "Feira de Santana - Terra Nova", "pe": 2},
{"rota": "Feira de Santana - Tucano", "pe": 3},
{"rota": "Feira de Santana - Uauá", "pe": 5},
{"rota": "Feira de Santana - Ubaíra", "pe": 3},
{"rota": "Feira de Santana - Uibaí", "pe": 2},
{"rota": "Feira de Santana - Umburanas", "pe": 2},
{"rota": "Feira de Santana - Utinga", "pe": 2},
{"rota": "Feira de Santana - Valença", "pe": 2},
{"rota": "Feira de Santana - Valente", "pe": 2},
{"rota": "Feira de Santana - Várzea Da Roça", "pe": 2},
{"rota": "Feira de Santana - Várzea Do Poço", "pe": 2},
{"rota": "Feira de Santana - Várzea Nova", "pe": 5},
{"rota": "Feira de Santana - Varzedo", "pe": 3},
{"rota": "Feira de Santana - Vera Cruz", "pe": 5},
{"rota": "Feira de Santana - Wagner", "pe": 2},
{"rota": "Feira de Santana - Wanderley", "pe": 3},
{"rota": "Feira de Santana - Wenceslau Guimarães", "pe": 2},
{"rota": "Feira de Santana - Xique-Xique", "pe": 3},
{"rota": "Simões Filho - Camaçari", "pe": 1},
{"rota": "Simões Filho - Candeias", "pe": 2},
{"rota": "Simões Filho - Dias D'Ávila", "pe": 1},
{"rota": "Simões Filho - Lauro De Freitas", "pe": 1},
{"rota": "Simões Filho - Madre De Deus", "pe": 3},
{"rota": "Simões Filho - Mata De São João", "pe": 3},
{"rota": "Simões Filho - Pojuca", "pe": 2},
{"rota": "Simões Filho - Salvador", "pe": 1},
{"rota": "Simões Filho - São Francisco Do Conde", "pe": 4},
{"rota": "Simões Filho - São Sebastião Do Passé", "pe": 2},
{"rota": "Simões Filho - Simões Filho", "pe": 1},
{"rota": "Vitória da Conquista - Aiquara", "pe": 6},
{"rota": "Vitória da Conquista - Alcobaça", "pe": 6},
{"rota": "Vitória da Conquista - Almadina", "pe": 6},
{"rota": "Vitória da Conquista - Anagé", "pe": 4},
{"rota": "Vitória da Conquista - Apuarema", "pe": 6},
{"rota": "Vitória da Conquista - Aracatu", "pe": 6},
{"rota": "Vitória da Conquista - Arataca", "pe": 6},
{"rota": "Vitória da Conquista - Aurelino Leal", "pe": 6},
{"rota": "Vitória da Conquista - Barra Da Estiva", "pe": 6},
{"rota": "Vitória da Conquista - Barra Do Choça", "pe": 4},
{"rota": "Vitória da Conquista - Barra Do Rocha", "pe": 6},
{"rota": "Vitória da Conquista - Barro Preto", "pe": 6},
{"rota": "Vitória da Conquista - Belmonte", "pe": 6},
{"rota": "Vitória da Conquista - Belo Campo", "pe": 6},
{"rota": "Vitória da Conquista - Boa Nova", "pe": 6},
{"rota": "Vitória da Conquista - Bom Jesus Da Lapa", "pe": 6},
{"rota": "Vitória da Conquista - Bom Jesus Da Serra", "pe": 6},
{"rota": "Vitória da Conquista - Boquira", "pe": 6},
{"rota": "Vitória da Conquista - Botuporã", "pe": 6},
{"rota": "Vitória da Conquista - Brejolândia", "pe": 6},
{"rota": "Vitória da Conquista - Brumado", "pe": 6},
{"rota": "Vitória da Conquista - Buerarema", "pe": 6},
{"rota": "Vitória da Conquista - Caatiba", "pe": 6},
{"rota": "Vitória da Conquista - Caculé", "pe": 6},
{"rota": "Vitória da Conquista - Caetanos", "pe": 6},
{"rota": "Vitória da Conquista - Caetité", "pe": 6},
{"rota": "Vitória da Conquista - Camacan", "pe": 6},
{"rota": "Vitória da Conquista - Canápolis", "pe": 6},
{"rota": "Vitória da Conquista - Canavieiras", "pe": 6},
{"rota": "Vitória da Conquista - Candiba", "pe": 6},
{"rota": "Vitória da Conquista - Cândido Sales", "pe": 6},
{"rota": "Vitória da Conquista - Caraíbas", "pe": 6},
{"rota": "Vitória da Conquista - Caravelas", "pe": 6},
{"rota": "Vitória da Conquista - Carinhanha", "pe": 6},
{"rota": "Vitória da Conquista - Caturama", "pe": 6},
{"rota": "Vitória da Conquista - Coaraci", "pe": 6},
{"rota": "Vitória da Conquista - Cocos", "pe": 6},
{"rota": "Vitória da Conquista - Condeúba", "pe": 6},
{"rota": "Vitória da Conquista - Contendas Do Sincorá", "pe": 6},
{"rota": "Vitória da Conquista - Cordeiros", "pe": 6},
{"rota": "Vitória da Conquista - Coribe", "pe": 6},
{"rota": "Vitória da Conquista - Correntina", "pe": 6},
{"rota": "Vitória da Conquista - Dário Meira", "pe": 6},
{"rota": "Vitória da Conquista - Dom Basílio", "pe": 6},
{"rota": "Vitória da Conquista - Encruzilhada", "pe": 6},
{"rota": "Vitória da Conquista - Érico Cardoso", "pe": 6},
{"rota": "Vitória da Conquista - Eunápolis", "pe": 6},
{"rota": "Vitória da Conquista - Feira Da Mata", "pe": 6},
{"rota": "Vitória da Conquista - Firmino Alves", "pe": 6},
{"rota": "Vitória da Conquista - Floresta Azul", "pe": 6},
{"rota": "Vitória da Conquista - Gongogi", "pe": 6},
{"rota": "Vitória da Conquista - Guajeru", "pe": 6},
{"rota": "Vitória da Conquista - Guanambi", "pe": 6},
{"rota": "Vitória da Conquista - Guaratinga", "pe": 6},
{"rota": "Vitória da Conquista - Ibiassucê", "pe": 6},
{"rota": "Vitória da Conquista - Ibicaraí", "pe": 6},
{"rota": "Vitória da Conquista - Ibicoara", "pe": 6},
{"rota": "Vitória da Conquista - Ibicuí", "pe": 6},
{"rota": "Vitória da Conquista - Ibipitanga", "pe": 6},
{"rota": "Vitória da Conquista - Ibirapitanga", "pe": 6},
{"rota": "Vitória da Conquista - Ibirapuã", "pe": 6},
{"rota": "Vitória da Conquista - Ibirataia", "pe": 6},
{"rota": "Vitória da Conquista - Igaporã", "pe": 6},
{"rota": "Vitória da Conquista - Iguaí", "pe": 6},
{"rota": "Vitória da Conquista - Ilhéus", "pe": 6},
{"rota": "Vitória da Conquista - Ipiaú", "pe": 6},
{"rota": "Vitória da Conquista - Iramaia", "pe": 6},
{"rota": "Vitória da Conquista - Itabela", "pe": 6},
{"rota": "Vitória da Conquista - Itabuna", "pe": 6},
{"rota": "Vitória da Conquista - Itacaré", "pe": 6},
{"rota": "Vitória da Conquista - Itagi", "pe": 6},
{"rota": "Vitória da Conquista - Itagibá", "pe": 6},
{"rota": "Vitória da Conquista - Itagimirim", "pe": 6},
{"rota": "Vitória da Conquista - Itaju Do Colônia", "pe": 6},
{"rota": "Vitória da Conquista - Itajuípe", "pe": 6},
{"rota": "Vitória da Conquista - Itamaraju", "pe": 6},
{"rota": "Vitória da Conquista - Itamari", "pe": 6},
{"rota": "Vitória da Conquista - Itambé", "pe": 4},
{"rota": "Vitória da Conquista - Itanhém", "pe": 6},
{"rota": "Vitória da Conquista - Itapé", "pe": 6},
{"rota": "Vitória da Conquista - Itapebi", "pe": 6},
{"rota": "Vitória da Conquista - Itapetinga", "pe": 6},
{"rota": "Vitória da Conquista - Itapitanga", "pe": 6},
{"rota": "Vitória da Conquista - Itarantim", "pe": 6},
{"rota": "Vitória da Conquista - Itororó", "pe": 6},
{"rota": "Vitória da Conquista - Ituaçu", "pe": 6},
{"rota": "Vitória da Conquista - Iuiu", "pe": 6},
{"rota": "Vitória da Conquista - Jaborandi", "pe": 6},
{"rota": "Vitória da Conquista - Jacaraci", "pe": 6},
{"rota": "Vitória da Conquista - Jaguaquara", "pe": 6},
{"rota": "Vitória da Conquista - Jequié", "pe": 6},
{"rota": "Vitória da Conquista - Jitaúna", "pe": 6},
{"rota": "Vitória da Conquista - Jucuruçu", "pe": 6},
{"rota": "Vitória da Conquista - Jussari", "pe": 6},
{"rota": "Vitória da Conquista - Jussiape", "pe": 6},
{"rota": "Vitória da Conquista - Lafaiete Coutinho", "pe": 6},
{"rota": "Vitória da Conquista - Lagoa Real", "pe": 6},
{"rota": "Vitória da Conquista - Lajedão", "pe": 6},
{"rota": "Vitória da Conquista - Lajedo Do Tabocal", "pe": 6},
{"rota": "Vitória da Conquista - Licínio De Almeida", "pe": 6},
{"rota": "Vitória da Conquista - Livramento De Nossa Senhora", "pe": 6},
{"rota": "Vitória da Conquista - Macarani", "pe": 6},
{"rota": "Vitória da Conquista - Macaúbas", "pe": 6},
{"rota": "Vitória da Conquista - Maetinga", "pe": 6},
{"rota": "Vitória da Conquista - Maiquinique", "pe": 6},
{"rota": "Vitória da Conquista - Malhada", "pe": 6},
{"rota": "Vitória da Conquista - Malhada De Pedras", "pe": 6},
{"rota": "Vitória da Conquista - Manoel Vitorino", "pe": 6},
{"rota": "Vitória da Conquista - Maracás", "pe": 6},
{"rota": "Vitória da Conquista - Maraú", "pe": 6},
{"rota": "Vitória da Conquista - Mascote", "pe": 6},
{"rota": "Vitória da Conquista - Matina", "pe": 6},
{"rota": "Vitória da Conquista - Medeiros Neto", "pe": 6},
{"rota": "Vitória da Conquista - Mirante", "pe": 6},
{"rota": "Vitória da Conquista - Morpará", "pe": 6},
{"rota": "Vitória da Conquista - Mortugaba", "pe": 6},
{"rota": "Vitória da Conquista - Mucuri", "pe": 6},
{"rota": "Vitória da Conquista - Nova Canaã", "pe": 6},
{"rota": "Vitória da Conquista - Nova Viçosa", "pe": 6},
{"rota": "Vitória da Conquista - Palmas De Monte Alto", "pe": 6},
{"rota": "Vitória da Conquista - Paramirim", "pe": 6},
{"rota": "Vitória da Conquista - Paratinga", "pe": 6},
{"rota": "Vitória da Conquista - Pau Brasil", "pe": 6},
{"rota": "Vitória da Conquista - Pindaí", "pe": 6},
{"rota": "Vitória da Conquista - Piripá", "pe": 6},
{"rota": "Vitória da Conquista - Planaltino", "pe": 6},
{"rota": "Vitória da Conquista - Planalto", "pe": 6},
{"rota": "Vitória da Conquista - Poções", "pe": 6},
{"rota": "Vitória da Conquista - Porto Seguro", "pe": 6},
{"rota": "Vitória da Conquista - Potiraguá", "pe": 6},
{"rota": "Vitória da Conquista - Prado", "pe": 6},
{"rota": "Vitória da Conquista - Presidente Jânio Quadros", "pe": 6},
{"rota": "Vitória da Conquista - Riacho De Santana", "pe": 6},
{"rota": "Vitória da Conquista - Ribeirão Do Largo", "pe": 6},
{"rota": "Vitória da Conquista - Rio De Contas", "pe": 6},
{"rota": "Vitória da Conquista - Rio Do Antônio", "pe": 6},
{"rota": "Vitória da Conquista - Rio Do Pires", "pe": 6},
{"rota": "Vitória da Conquista - Santa Cruz Cabrália", "pe": 6},
{"rota": "Vitória da Conquista - Santa Cruz Da Vitória", "pe": 6},
{"rota": "Vitória da Conquista - Santa Luzia", "pe": 6},
{"rota": "Vitória da Conquista - Santa Maria Da Vitória", "pe": 6},
{"rota": "Vitória da Conquista - Santana", "pe": 6},
{"rota": "Vitória da Conquista - São Félix Do Coribe", "pe": 6},
{"rota": "Vitória da Conquista - São José Da Vitória", "pe": 6},
{"rota": "Vitória da Conquista - Sebastião Laranjeiras", "pe": 6},
{"rota": "Vitória da Conquista - Serra Do Ramalho", "pe": 6},
{"rota": "Vitória da Conquista - Serra Dourada", "pe": 6},
{"rota": "Vitória da Conquista - Sítio Do Mato", "pe": 6},
{"rota": "Vitória da Conquista - Tabocas Do Brejo Velho", "pe": 6},
{"rota": "Vitória da Conquista - Tanhaçu", "pe": 6},
{"rota": "Vitória da Conquista - Tanque Novo", "pe": 6},
{"rota": "Vitória da Conquista - Teixeira De Freitas", "pe": 6},
{"rota": "Vitória da Conquista - Tremedal", "pe": 6},
{"rota": "Vitória da Conquista - Ubaitaba", "pe": 6},
{"rota": "Vitória da Conquista - Ubatã", "pe": 6},
{"rota": "Vitória da Conquista - Una", "pe": 6},
{"rota": "Vitória da Conquista - Urandi", "pe": 6},
{"rota": "Vitória da Conquista - Uruçuca", "pe": 6},
{"rota": "Vitória da Conquista - Vereda", "pe": 6},
{"rota": "Vitória da Conquista - Vitória Da Conquista", "pe": 1},
{"rota": "Eusébio - Aquiraz", "pe": 2},
{"rota": "Eusébio - Caucaia", "pe": 2},
{"rota": "Eusébio - Eusébio", "pe": 2},
{"rota": "Eusébio - Fortaleza", "pe": 2},
{"rota": "Eusébio - Horizonte", "pe": 2},
{"rota": "Eusébio - Itaitinga", "pe": 2},
{"rota": "Eusébio - Maracanaú", "pe": 2},
{"rota": "Eusébio - São Gonçalo Do Amarante", "pe": 3},
{"rota": "Viana - Cariacica", "pe": 1},
{"rota": "Viana - Guarapari", "pe": 4},
{"rota": "Viana - Serra", "pe": 1},
{"rota": "Viana - Viana", "pe": 1},
{"rota": "Viana - Vila Velha", "pe": 1},
{"rota": "Viana - Vitória", "pe": 1},
{"rota": "São Luís - Paço Do Lumiar", "pe": 1},
{"rota": "São Luís - Raposa", "pe": 1},
{"rota": "São Luís - São José De Ribamar", "pe": 1},
{"rota": "São Luís - São Luís", "pe": 1},
{"rota": "Contagem - Belo Horizonte", "pe": 1},
{"rota": "Contagem - Betim", "pe": 1},
{"rota": "Contagem - Brumadinho", "pe": 1},
{"rota": "Contagem - Confins", "pe": 1},
{"rota": "Contagem - Contagem", "pe": 1},
{"rota": "Contagem - Esmeraldas", "pe": 1},
{"rota": "Contagem - Ibirité", "pe": 1},
{"rota": "Contagem - Itabirito", "pe": 1},
{"rota": "Contagem - Lagoa Santa", "pe": 2},
{"rota": "Contagem - Mário Campos", "pe": 1},
{"rota": "Contagem - Mateus Leme", "pe": 1},
{"rota": "Contagem - Matozinhos", "pe": 4},
{"rota": "Contagem - Moeda", "pe": 2},
{"rota": "Contagem - Nova Lima", "pe": 1},
{"rota": "Contagem - Pará De Minas", "pe": 2},
{"rota": "Contagem - Pedro Leopoldo", "pe": 1},
{"rota": "Contagem - Raposos", "pe": 1},
{"rota": "Contagem - Ribeirão Das Neves", "pe": 1},
{"rota": "Contagem - Rio Acima", "pe": 1},
{"rota": "Contagem - Sabará", "pe": 1},
{"rota": "Contagem - Santa Luzia", "pe": 1},
{"rota": "Contagem - São Joaquim De Bicas", "pe": 1},
{"rota": "Contagem - São José Da Lapa", "pe": 1},
{"rota": "Contagem - Sete Lagoas", "pe": 2},
{"rota": "Contagem - Vespasiano", "pe": 1},
{"rota": "Campina Grande - Bayeux", "pe": 1},
{"rota": "Campina Grande - Caaporã", "pe": 1},
{"rota": "Campina Grande - Cabedelo", "pe": 2},
{"rota": "Campina Grande - Campina Grande", "pe": 2},
{"rota": "Campina Grande - Conde", "pe": 1},
{"rota": "Campina Grande - Cruz Do Espírito Santo", "pe": 1},
{"rota": "Campina Grande - João Pessoa", "pe": 1},
{"rota": "Campina Grande - Juripiranga", "pe": 2},
{"rota": "Campina Grande - Mamanguape", "pe": 2},
{"rota": "Campina Grande - Mataraca", "pe": 2},
{"rota": "Campina Grande - Pitimbu", "pe": 1},
{"rota": "Campina Grande - Santa Rita", "pe": 2},
{"rota": "Cabo de Santo Agostinho - Abreu E Lima", "pe": 2},
{"rota": "Cabo de Santo Agostinho - Araçoiaba", "pe": 2},
{"rota": "Cabo de Santo Agostinho - Cabo De Santo Agostinho", "pe": 2},
{"rota": "Cabo de Santo Agostinho - Camaragibe", "pe": 2},
{"rota": "Cabo de Santo Agostinho - Fernando De Noronha", "pe": 15},
{"rota": "Cabo de Santo Agostinho - Igarassu", "pe": 2},
{"rota": "Cabo de Santo Agostinho - Ipojuca", "pe": 2},
{"rota": "Cabo de Santo Agostinho - Ilha De Itamaracá", "pe": 2},
{"rota": "Cabo de Santo Agostinho - Itapissuma", "pe": 2},
{"rota": "Cabo de Santo Agostinho - Jaboatão Dos Guararapes", "pe": 1},
{"rota": "Cabo de Santo Agostinho - Moreno", "pe": 2},
{"rota": "Cabo de Santo Agostinho - Olinda", "pe": 1},
{"rota": "Cabo de Santo Agostinho - Paulista", "pe": 2},
{"rota": "Cabo de Santo Agostinho - Recife", "pe": 1},
{"rota": "Cabo de Santo Agostinho - São Lourenço Da Mata", "pe": 2},
{"rota": "Teresina - Teresina", "pe": 1},
{"rota": "Cascavel - Anahy", "pe": 4},
{"rota": "Cascavel - Assis Chateaubriand", "pe": 2},
{"rota": "Cascavel - Boa Vista Da Aparecida", "pe": 3},
{"rota": "Cascavel - Braganey", "pe": 4},
{"rota": "Cascavel - Cafelândia", "pe": 4},
{"rota": "Cascavel - Capitão Leônidas Marques", "pe": 3},
{"rota": "Cascavel - Cascavel", "pe": 1},
{"rota": "Cascavel - Catanduvas", "pe": 2},
{"rota": "Cascavel - Céu Azul", "pe": 3},
{"rota": "Cascavel - Corbélia", "pe": 3},
{"rota": "Cascavel - Diamante Do Sul", "pe": 4},
{"rota": "Cascavel - Diamante D'Oeste", "pe": 4},
{"rota": "Cascavel - Entre Rios Do Oeste", "pe": 3},
{"rota": "Cascavel - Formosa Do Oeste", "pe": 3},
{"rota": "Cascavel - Foz Do Iguaçu", "pe": 2},
{"rota": "Cascavel - Guaraniaçu", "pe": 2},
{"rota": "Cascavel - Ibema", "pe": 2},
{"rota": "Cascavel - Iguatu", "pe": 4},
{"rota": "Cascavel - Iracema Do Oeste", "pe": 2},
{"rota": "Cascavel - Itaipulândia", "pe": 3},
{"rota": "Cascavel - Jesuítas", "pe": 2},
{"rota": "Cascavel - Lindoeste", "pe": 3},
{"rota": "Cascavel - Marechal Cândido Rondon", "pe": 2},
{"rota": "Cascavel - Maripá", "pe": 2},
{"rota": "Cascavel - Matelândia", "pe": 3},
{"rota": "Cascavel - Medianeira", "pe": 3},
{"rota": "Cascavel - Mercedes", "pe": 3},
{"rota": "Cascavel - Missal", "pe": 3},
{"rota": "Cascavel - Nova Aurora", "pe": 3},
{"rota": "Cascavel - Nova Laranjeiras", "pe": 4},
{"rota": "Cascavel - Nova Santa Rosa", "pe": 2},
{"rota": "Cascavel - Ouro Verde Do Oeste", "pe": 2},
{"rota": "Cascavel - Palotina", "pe": 2},
{"rota": "Cascavel - Pato Bragado", "pe": 2},
{"rota": "Cascavel - Porto Barreiro", "pe": 3},
{"rota": "Cascavel - Quatro Pontes", "pe": 2},
{"rota": "Cascavel - Quedas Do Iguaçu", "pe": 1},
{"rota": "Cascavel - Ramilândia", "pe": 4},
{"rota": "Cascavel - Santa Helena", "pe": 3},
{"rota": "Cascavel - Santa Lúcia", "pe": 3},
{"rota": "Cascavel - Santa Tereza Do Oeste", "pe": 3},
{"rota": "Cascavel - Santa Terezinha De Itaipu", "pe": 3},
{"rota": "Cascavel - São José Das Palmeiras", "pe": 3},
{"rota": "Cascavel - São Miguel Do Iguaçu", "pe": 3},
{"rota": "Cascavel - São Pedro Do Iguaçu", "pe": 3},
{"rota": "Cascavel - Serranópolis Do Iguaçu", "pe": 4},
{"rota": "Cascavel - Toledo", "pe": 2},
{"rota": "Cascavel - Três Barras Do Paraná", "pe": 1},
{"rota": "Cascavel - Tupãssi", "pe": 3},
{"rota": "Cascavel - Ubiratã", "pe": 3},
{"rota": "Cascavel - Vera Cruz Do Oeste", "pe": 4},
{"rota": "Curitiba - Agudos Do Sul", "pe": 3},
{"rota": "Curitiba - Almirante Tamandaré", "pe": 1},
{"rota": "Curitiba - Arapoti", "pe": 3},
{"rota": "Curitiba - Araucária", "pe": 1},
{"rota": "Curitiba - Campina Grande Do Sul", "pe": 1},
{"rota": "Curitiba - Campo Largo", "pe": 3},
{"rota": "Curitiba - Carambeí", "pe": 3},
{"rota": "Curitiba - Castro", "pe": 3},
{"rota": "Curitiba - Colombo", "pe": 1},
{"rota": "Curitiba - Curitiba", "pe": 1},
{"rota": "Curitiba - Fazenda Rio Grande", "pe": 1},
{"rota": "Curitiba - Fernandes Pinheiro", "pe": 4},
{"rota": "Curitiba - Figueira", "pe": 3},
{"rota": "Curitiba - Imbituva", "pe": 4},
{"rota": "Curitiba - Ipiranga", "pe": 4},
{"rota": "Curitiba - Irati", "pe": 3},
{"rota": "Curitiba - Ivaí", "pe": 4},
{"rota": "Curitiba - Jaguariaíva", "pe": 4},
{"rota": "Curitiba - Mandirituba", "pe": 2},
{"rota": "Curitiba - Palmeira", "pe": 3},
{"rota": "Curitiba - Pinhais", "pe": 1},
{"rota": "Curitiba - Piraí Do Sul", "pe": 2},
{"rota": "Curitiba - Piraquara", "pe": 1},
{"rota": "Curitiba - Ponta Grossa", "pe": 1},
{"rota": "Curitiba - Porto Amazonas", "pe": 3},
{"rota": "Curitiba - Quatro Barras", "pe": 1},
{"rota": "Curitiba - Quitandinha", "pe": 2},
{"rota": "Curitiba - Rebouças", "pe": 4},
{"rota": "Curitiba - Rio Azul", "pe": 4},
{"rota": "Curitiba - São José Da Boa Vista", "pe": 3},
{"rota": "Curitiba - São José Dos Pinhais", "pe": 1},
{"rota": "Curitiba - Sengés", "pe": 4},
{"rota": "Curitiba - Teixeira Soares", "pe": 4},
{"rota": "Curitiba - Ventania", "pe": 3},
{"rota": "Curitiba - Wenceslau Braz", "pe": 3},
{"rota": "Francisco Beltrão - Ampére", "pe": 2},
{"rota": "Francisco Beltrão - Barracão", "pe": 3},
{"rota": "Francisco Beltrão - Bela Vista Da Caroba", "pe": 3},
{"rota": "Francisco Beltrão - Boa Esperança Do Iguaçu", "pe": 3},
{"rota": "Francisco Beltrão - Bom Jesus Do Sul", "pe": 3},
{"rota": "Francisco Beltrão - Capanema", "pe": 3},
{"rota": "Francisco Beltrão - Cruzeiro Do Iguaçu", "pe": 3},
{"rota": "Francisco Beltrão - Dois Vizinhos", "pe": 3},
{"rota": "Francisco Beltrão - Enéas Marques", "pe": 3},
{"rota": "Francisco Beltrão - Flor Da Serra Do Sul", "pe": 3},
{"rota": "Francisco Beltrão - Francisco Beltrão", "pe": 3},
{"rota": "Francisco Beltrão - Manfrinópolis", "pe": 3},
{"rota": "Francisco Beltrão - Marmeleiro", "pe": 3},
{"rota": "Francisco Beltrão - Nova Esperança Do Sudoeste", "pe": 3},
{"rota": "Francisco Beltrão - Nova Prata Do Iguaçu", "pe": 3},
{"rota": "Francisco Beltrão - Pérola D'Oeste", "pe": 3},
{"rota": "Francisco Beltrão - Pinhal De São Bento", "pe": 3},
{"rota": "Francisco Beltrão - Planalto", "pe": 3},
{"rota": "Francisco Beltrão - Pranchita", "pe": 3},
{"rota": "Francisco Beltrão - Realeza", "pe": 3},
{"rota": "Francisco Beltrão - Renascença", "pe": 3},
{"rota": "Francisco Beltrão - Salgado Filho", "pe": 3},
{"rota": "Francisco Beltrão - Salto Do Lontra", "pe": 3},
{"rota": "Francisco Beltrão - Santa Izabel Do Oeste", "pe": 3},
{"rota": "Francisco Beltrão - Santo Antônio Do Sudoeste", "pe": 3},
{"rota": "Francisco Beltrão - São Jorge D'Oeste", "pe": 3},
{"rota": "Francisco Beltrão - Verê", "pe": 3},
{"rota": "Guarapuava - Boa Ventura De São Roque", "pe": 4},
{"rota": "Guarapuava - Campina Do Simão", "pe": 4},
{"rota": "Guarapuava - Cândido De Abreu", "pe": 3},
{"rota": "Guarapuava - Candói", "pe": 3},
{"rota": "Guarapuava - Cantagalo", "pe": 4},
{"rota": "Guarapuava - Espigão Alto Do Iguaçu", "pe": 4},
{"rota": "Guarapuava - Foz Do Jordão", "pe": 3},
{"rota": "Guarapuava - Goioxim", "pe": 4},
{"rota": "Guarapuava - Guamiranga", "pe": 4},
{"rota": "Guarapuava - Guarapuava", "pe": 1},
{"rota": "Guarapuava - Inácio Martins", "pe": 4},
{"rota": "Guarapuava - Laranjal", "pe": 4},
{"rota": "Guarapuava - Laranjeiras Do Sul", "pe": 4},
{"rota": "Guarapuava - Marquinho", "pe": 4},
{"rota": "Guarapuava - Palmital", "pe": 4},
{"rota": "Guarapuava - Pinhão", "pe": 3},
{"rota": "Guarapuava - Pitanga", "pe": 3},
{"rota": "Guarapuava - Prudentópolis", "pe": 3},
{"rota": "Guarapuava - Reserva Do Iguaçu", "pe": 4},
{"rota": "Guarapuava - Rio Bonito Do Iguaçu", "pe": 4},
{"rota": "Guarapuava - Santa Maria Do Oeste", "pe": 3},
{"rota": "Guarapuava - Turvo", "pe": 3},
{"rota": "Guarapuava - Virmond", "pe": 4},
{"rota": "Londrina - Abatiá", "pe": 3},
{"rota": "Londrina - Alvorada Do Sul", "pe": 3},
{"rota": "Londrina - Andirá", "pe": 3},
{"rota": "Londrina - Apucarana", "pe": 3},
{"rota": "Londrina - Arapongas", "pe": 3},
{"rota": "Londrina - Arapuã", "pe": 3},
{"rota": "Londrina - Ariranha Do Ivaí", "pe": 3},
{"rota": "Londrina - Assaí", "pe": 3},
{"rota": "Londrina - Astorga", "pe": 4},
{"rota": "Londrina - Bandeirantes", "pe": 3},
{"rota": "Londrina - Barra Do Jacaré", "pe": 3},
{"rota": "Londrina - Bela Vista Do Paraíso", "pe": 3},
{"rota": "Londrina - Bom Sucesso", "pe": 3},
{"rota": "Londrina - Borrazópolis", "pe": 3},
{"rota": "Londrina - Califórnia", "pe": 3},
{"rota": "Londrina - Cambará", "pe": 3},
{"rota": "Londrina - Cambé", "pe": 1},
{"rota": "Londrina - Cambira", "pe": 3},
{"rota": "Londrina - Carlópolis", "pe": 3},
{"rota": "Londrina - Centenário Do Sul", "pe": 3},
{"rota": "Londrina - Congonhinhas", "pe": 3},
{"rota": "Londrina - Conselheiro Mairinck", "pe": 3},
{"rota": "Londrina - Cornélio Procópio", "pe": 3},
{"rota": "Londrina - Cruzmaltina", "pe": 3},
{"rota": "Londrina - Faxinal", "pe": 3},
{"rota": "Londrina - Florestópolis", "pe": 3},
{"rota": "Londrina - Grandes Rios", "pe": 3},
{"rota": "Londrina - Guapirama", "pe": 3},
{"rota": "Londrina - Ibaiti", "pe": 3},
{"rota": "Londrina - Ibiporã", "pe": 1},
{"rota": "Londrina - Itambaracá", "pe": 3},
{"rota": "Londrina - Ivaiporã", "pe": 3},
{"rota": "Londrina - Jaboti", "pe": 3},
{"rota": "Londrina - Jacarezinho", "pe": 3},
{"rota": "Londrina - Jaguapitã", "pe": 3},
{"rota": "Londrina - Japira", "pe": 3},
{"rota": "Londrina - Jardim Alegre", "pe": 3},
{"rota": "Londrina - Jataizinho", "pe": 1},
{"rota": "Londrina - Joaquim Távora", "pe": 3},
{"rota": "Londrina - Jundiaí Do Sul", "pe": 3},
{"rota": "Londrina - Kaloré", "pe": 3},
{"rota": "Londrina - Leópolis", "pe": 3},
{"rota": "Londrina - Lidianópolis", "pe": 3},
{"rota": "Londrina - Londrina", "pe": 1},
{"rota": "Londrina - Lunardelli", "pe": 3},
{"rota": "Londrina - Lupionópolis", "pe": 3},
{"rota": "Londrina - Manoel Ribas", "pe": 3},
{"rota": "Londrina - Marilândia Do Sul", "pe": 3},
{"rota": "Londrina - Marumbi", "pe": 3},
{"rota": "Londrina - Mauá Da Serra", "pe": 3},
{"rota": "Londrina - Miraselva", "pe": 3},
{"rota": "Londrina - Nova América Da Colina", "pe": 3},
{"rota": "Londrina - Nova Fátima", "pe": 3},
{"rota": "Londrina - Nova Santa Bárbara", "pe": 3},
{"rota": "Londrina - Nova Tebas", "pe": 4},
{"rota": "Londrina - Novo Itacolomi", "pe": 3},
{"rota": "Londrina - Pinhalão", "pe": 3},
{"rota": "Londrina - Pitangueiras", "pe": 4},
{"rota": "Londrina - Porecatu", "pe": 3},
{"rota": "Londrina - Prado Ferreira", "pe": 3},
{"rota": "Londrina - Primeiro De Maio", "pe": 3},
{"rota": "Londrina - Quatiguá", "pe": 3},
{"rota": "Londrina - Rancho Alegre", "pe": 3},
{"rota": "Londrina - Ribeirão Claro", "pe": 3},
{"rota": "Londrina - Ribeirão Do Pinhal", "pe": 3},
{"rota": "Londrina - Rio Bom", "pe": 3},
{"rota": "Londrina - Rio Branco Do Ivaí", "pe": 3},
{"rota": "Londrina - Rolândia", "pe": 1},
{"rota": "Londrina - Rosário Do Ivaí", "pe": 3},
{"rota": "Londrina - Sabáudia", "pe": 3},
{"rota": "Londrina - Salto Do Itararé", "pe": 3},
{"rota": "Londrina - Santa Amélia", "pe": 3},
{"rota": "Londrina - Santa Cecília Do Pavão", "pe": 3},
{"rota": "Londrina - Santa Mariana", "pe": 3},
{"rota": "Londrina - Santana Do Itararé", "pe": 3},
{"rota": "Londrina - Santo Antônio Da Platina", "pe": 3},
{"rota": "Londrina - Santo Antônio Do Paraíso", "pe": 3},
{"rota": "Londrina - São Jerônimo Da Serra", "pe": 3},
{"rota": "Londrina - São João Do Ivaí", "pe": 3},
{"rota": "Londrina - São Pedro Do Ivaí", "pe": 3},
{"rota": "Londrina - São Sebastião Da Amoreira", "pe": 3},
{"rota": "Londrina - Sertaneja", "pe": 3},
{"rota": "Londrina - Sertanópolis", "pe": 3},
{"rota": "Londrina - Siqueira Campos", "pe": 3},
{"rota": "Londrina - Tamarana", "pe": 3},
{"rota": "Londrina - Tomazina", "pe": 3},
{"rota": "Londrina - Uraí", "pe": 3},
{"rota": "Maringá - Altamira Do Paraná", "pe": 4},
{"rota": "Maringá - Alto Paraíso", "pe": 4},
{"rota": "Maringá - Alto Paraná", "pe": 1},
{"rota": "Maringá - Alto Piquiri", "pe": 3},
{"rota": "Maringá - Altônia", "pe": 3},
{"rota": "Maringá - Amaporã", "pe": 3},
{"rota": "Maringá - Ângulo", "pe": 4},
{"rota": "Maringá - Araruna", "pe": 2},
{"rota": "Maringá - Atalaia", "pe": 3},
{"rota": "Maringá - Barbosa Ferraz", "pe": 3},
{"rota": "Maringá - Boa Esperança", "pe": 4},
{"rota": "Maringá - Brasilândia Do Sul", "pe": 4},
{"rota": "Maringá - Cafeara", "pe": 4},
{"rota": "Maringá - Cafezal Do Sul", "pe": 4},
{"rota": "Maringá - Campina Da Lagoa", "pe": 3},
{"rota": "Maringá - Campo Mourão", "pe": 1},
{"rota": "Maringá - Cianorte", "pe": 1},
{"rota": "Maringá - Cidade Gaúcha", "pe": 3},
{"rota": "Maringá - Colorado", "pe": 2},
{"rota": "Maringá - Corumbataí Do Sul", "pe": 3},
{"rota": "Maringá - Cruzeiro Do Oeste", "pe": 3},
{"rota": "Maringá - Cruzeiro Do Sul", "pe": 3},
{"rota": "Maringá - Diamante Do Norte", "pe": 2},
{"rota": "Maringá - Douradina", "pe": 3},
{"rota": "Maringá - Doutor Camargo", "pe": 2},
{"rota": "Maringá - Engenheiro Beltrão", "pe": 2},
{"rota": "Maringá - Esperança Nova", "pe": 3},
{"rota": "Maringá - Farol", "pe": 4},
{"rota": "Maringá - Fênix", "pe": 4},
{"rota": "Maringá - Floraí", "pe": 2},
{"rota": "Maringá - Floresta", "pe": 1},
{"rota": "Maringá - Flórida", "pe": 3},
{"rota": "Maringá - Francisco Alves", "pe": 3},
{"rota": "Maringá - Godoy Moreira", "pe": 3},
{"rota": "Maringá - Goioerê", "pe": 3},
{"rota": "Maringá - Guaíra", "pe": 3},
{"rota": "Maringá - Guairaçá", "pe": 2},
{"rota": "Maringá - Guaporema", "pe": 4},
{"rota": "Maringá - Guaraci", "pe": 3},
{"rota": "Maringá - Iguaraçu", "pe": 3},
{"rota": "Maringá - Inajá", "pe": 3},
{"rota": "Maringá - Indianópolis", "pe": 4},
{"rota": "Maringá - Iporã", "pe": 2},
{"rota": "Maringá - Iretama", "pe": 4},
{"rota": "Maringá - Itaguajé", "pe": 2},
{"rota": "Maringá - Itambé", "pe": 2},
{"rota": "Maringá - Itaúna Do Sul", "pe": 2},
{"rota": "Maringá - Ivaté", "pe": 4},
{"rota": "Maringá - Ivatuba", "pe": 4},
{"rota": "Maringá - Jandaia Do Sul", "pe": 4},
{"rota": "Maringá - Janiópolis", "pe": 3},
{"rota": "Maringá - Japurá", "pe": 3},
{"rota": "Maringá - Jardim Olinda", "pe": 4},
{"rota": "Maringá - Juranda", "pe": 4},
{"rota": "Maringá - Jussara", "pe": 3},
{"rota": "Maringá - Loanda", "pe": 2},
{"rota": "Maringá - Lobato", "pe": 2},
{"rota": "Maringá - Luiziana", "pe": 2},
{"rota": "Maringá - Mamborê", "pe": 3},
{"rota": "Maringá - Mandaguaçu", "pe": 1},
{"rota": "Maringá - Mandaguari", "pe": 2},
{"rota": "Maringá - Maria Helena", "pe": 4},
{"rota": "Maringá - Marialva", "pe": 2},
{"rota": "Maringá - Marilena", "pe": 2},
{"rota": "Maringá - Mariluz", "pe": 4},
{"rota": "Maringá - Maringá", "pe": 1},
{"rota": "Maringá - Mato Rico", "pe": 4},
{"rota": "Maringá - Mirador", "pe": 3},
{"rota": "Maringá - Moreira Sales", "pe": 4},
{"rota": "Maringá - Munhoz De Melo", "pe": 3},
{"rota": "Maringá - Nossa Senhora Das Graças", "pe": 2},
{"rota": "Maringá - Nova Aliança Do Ivaí", "pe": 3},
{"rota": "Maringá - Nova Cantu", "pe": 4},
{"rota": "Maringá - Nova Esperança", "pe": 1},
{"rota": "Maringá - Nova Londrina", "pe": 2},
{"rota": "Maringá - Nova Olímpia", "pe": 3},
{"rota": "Maringá - Ourizona", "pe": 4},
{"rota": "Maringá - Paiçandu", "pe": 1},
{"rota": "Maringá - Paraíso Do Norte", "pe": 2},
{"rota": "Maringá - Paranacity", "pe": 3},
{"rota": "Maringá - Paranapoema", "pe": 3},
{"rota": "Maringá - Paranavaí", "pe": 1},
{"rota": "Maringá - Peabiru", "pe": 1},
{"rota": "Maringá - Perobal", "pe": 3},
{"rota": "Maringá - Pérola", "pe": 2},
{"rota": "Maringá - Planaltina Do Paraná", "pe": 3},
{"rota": "Maringá - Porto Rico", "pe": 3},
{"rota": "Maringá - Presidente Castelo Branco", "pe": 1},
{"rota": "Maringá - Quarto Centenário", "pe": 4},
{"rota": "Maringá - Querência Do Norte", "pe": 3},
{"rota": "Maringá - Quinta Do Sol", "pe": 3},
{"rota": "Maringá - Rancho Alegre D'Oeste", "pe": 4},
{"rota": "Maringá - Roncador", "pe": 4},
{"rota": "Maringá - Rondon", "pe": 3},
{"rota": "Maringá - Santa Cruz De Monte Castelo", "pe": 3},
{"rota": "Maringá - Santa Fé", "pe": 2},
{"rota": "Maringá - Santa Inês", "pe": 3},
{"rota": "Maringá - Santa Isabel Do Ivaí", "pe": 3},
{"rota": "Maringá - Santa Mônica", "pe": 3},
{"rota": "Maringá - Santo Antônio Do Caiuá", "pe": 3},
{"rota": "Maringá - Santo Inácio", "pe": 3},
{"rota": "Maringá - São Carlos Do Ivaí", "pe": 2},
{"rota": "Maringá - São João Do Caiuá", "pe": 3},
{"rota": "Maringá - São Jorge Do Ivaí", "pe": 4},
{"rota": "Maringá - São Jorge Do Patrocínio", "pe": 4},
{"rota": "Maringá - São Manoel Do Paraná", "pe": 4},
{"rota": "Maringá - São Pedro Do Paraná", "pe": 3},
{"rota": "Maringá - São Tomé", "pe": 3},
{"rota": "Maringá - Sarandi", "pe": 1},
{"rota": "Maringá - Tamboara", "pe": 3},
{"rota": "Maringá - Tapejara", "pe": 2},
{"rota": "Maringá - Tapira", "pe": 3},
{"rota": "Maringá - Terra Boa", "pe": 2},
{"rota": "Maringá - Terra Rica", "pe": 2},
{"rota": "Maringá - Terra Roxa", "pe": 3},
{"rota": "Maringá - Tuneiras Do Oeste", "pe": 3},
{"rota": "Maringá - Umuarama", "pe": 2},
{"rota": "Maringá - Uniflor", "pe": 3},
{"rota": "Maringá - Xambrê", "pe": 2},
{"rota": "Pato Branco - Bom Sucesso Do Sul", "pe": 2},
{"rota": "Pato Branco - Chopinzinho", "pe": 2},
{"rota": "Pato Branco - Clevelândia", "pe": 2},
{"rota": "Pato Branco - Coronel Domingos Soares", "pe": 4},
{"rota": "Pato Branco - Coronel Vivida", "pe": 2},
{"rota": "Pato Branco - Honório Serpa", "pe": 4},
{"rota": "Pato Branco - Itapejara D'Oeste", "pe": 2},
{"rota": "Pato Branco - Mangueirinha", "pe": 3},
{"rota": "Pato Branco - Mariópolis", "pe": 3},
{"rota": "Pato Branco - Palmas", "pe": 3},
{"rota": "Pato Branco - Pato Branco", "pe": 1},
{"rota": "Pato Branco - São João", "pe": 2},
{"rota": "Pato Branco - Saudade Do Iguaçu", "pe": 2},
{"rota": "Pato Branco - Sulina", "pe": 2},
{"rota": "Pato Branco - Vitorino", "pe": 1},
{"rota": "Rio Negro - Bela Vista Do Toldo", "pe": 3},
{"rota": "Rio Negro - Campo Do Tenente", "pe": 3},
{"rota": "Rio Negro - Canoinhas", "pe": 2},
{"rota": "Rio Negro - Itaiópolis", "pe": 2},
{"rota": "Rio Negro - Mafra", "pe": 1},
{"rota": "Rio Negro - Major Vieira", "pe": 2},
{"rota": "Rio Negro - Monte Castelo", "pe": 2},
{"rota": "Rio Negro - Papanduva", "pe": 2},
{"rota": "Rio Negro - Piên", "pe": 3},
{"rota": "Rio Negro - Rio Negro", "pe": 1},
{"rota": "Rio Negro - São Bento Do Sul", "pe": 2},
{"rota": "Rio Negro - Três Barras", "pe": 2},
{"rota": "Telêmaco Borba - Curiúva", "pe": 4},
{"rota": "Telêmaco Borba - Imbaú", "pe": 4},
{"rota": "Telêmaco Borba - Ortigueira", "pe": 4},
{"rota": "Telêmaco Borba - Reserva", "pe": 4},
{"rota": "Telêmaco Borba - Sapopema", "pe": 3},
{"rota": "Telêmaco Borba - Telêmaco Borba", "pe": 1},
{"rota": "Telêmaco Borba - Tibagi", "pe": 4},
{"rota": "Belford Roxo - Belford Roxo", "pe": 2},
{"rota": "Belford Roxo - Duque De Caxias", "pe": 2},
{"rota": "Belford Roxo - Itaboraí", "pe": 2},
{"rota": "Belford Roxo - Mesquita", "pe": 3},
{"rota": "Belford Roxo - Nilópolis", "pe": 2},
{"rota": "Belford Roxo - Niterói", "pe": 2},
{"rota": "Belford Roxo - Nova Iguaçu", "pe": 2},
{"rota": "Belford Roxo - Queimados", "pe": 3},
{"rota": "Belford Roxo - Rio De Janeiro", "pe": 2},
{"rota": "Belford Roxo - São Gonçalo", "pe": 2},
{"rota": "Belford Roxo - São João De Meriti", "pe": 2},
{"rota": "Parnamirim - Ceará-Mirim", "pe": 1},
{"rota": "Parnamirim - Extremoz", "pe": 1},
{"rota": "Parnamirim - Macaíba", "pe": 1},
{"rota": "Parnamirim - Monte Alegre", "pe": 1},
{"rota": "Parnamirim - Natal", "pe": 1},
{"rota": "Parnamirim - Nísia Floresta", "pe": 1},
{"rota": "Parnamirim - Parnamirim", "pe": 1},
{"rota": "Parnamirim - São Gonçalo Do Amarante", "pe": 2},
{"rota": "Parnamirim - São José De Mipibu", "pe": 1},
{"rota": "Alegrete - Alegrete", "pe": 1},
{"rota": "Alegrete - Manoel Viana", "pe": 4},
{"rota": "Alegrete - Quaraí", "pe": 4},
{"rota": "Camaquã - Amaral Ferrador", "pe": 4},
{"rota": "Camaquã - Arambaré", "pe": 4},
{"rota": "Camaquã - Barão Do Triunfo", "pe": 3},
{"rota": "Camaquã - Camaquã", "pe": 3},
{"rota": "Camaquã - Cerro Grande Do Sul", "pe": 3},
{"rota": "Camaquã - Chuvisca", "pe": 3},
{"rota": "Camaquã - Cristal", "pe": 4},
{"rota": "Camaquã - Dom Feliciano", "pe": 3},
{"rota": "Camaquã - Mariana Pimentel", "pe": 3},
{"rota": "Camaquã - Sentinela Do Sul", "pe": 3},
{"rota": "Camaquã - Sertão Santana", "pe": 3},
{"rota": "Camaquã - Tapes", "pe": 3},
{"rota": "Canoas - Alvorada", "pe": 1},
{"rota": "Canoas - Cachoeirinha", "pe": 1},
{"rota": "Canoas - Campo Bom", "pe": 1},
{"rota": "Canoas - Canoas", "pe": 1},
{"rota": "Canoas - Eldorado Do Sul", "pe": 1},
{"rota": "Canoas - Estância Velha", "pe": 1},
{"rota": "Canoas - Esteio", "pe": 1},
{"rota": "Canoas - Feliz", "pe": 2},
{"rota": "Canoas - Gravataí", "pe": 1},
{"rota": "Canoas - Guaíba", "pe": 1},
{"rota": "Canoas - Ivoti", "pe": 1},
{"rota": "Canoas - Nova Santa Rita", "pe": 1},
{"rota": "Canoas - Novo Hamburgo", "pe": 1},
{"rota": "Canoas - Portão", "pe": 1},
{"rota": "Canoas - Porto Alegre", "pe": 1},
{"rota": "Canoas - São Leopoldo", "pe": 1},
{"rota": "Canoas - Sapiranga", "pe": 1},
{"rota": "Canoas - Sapucaia Do Sul", "pe": 1},
{"rota": "Canoas - Triunfo", "pe": 1},
{"rota": "Canoas - Viamão", "pe": 1},
{"rota": "Caxias do Sul - Alto Feliz", "pe": 4},
{"rota": "Caxias do Sul - Barão", "pe": 3},
{"rota": "Caxias do Sul - Bento Gonçalves", "pe": 1},
{"rota": "Caxias do Sul - Carlos Barbosa", "pe": 1},
{"rota": "Caxias do Sul - Caxias Do Sul", "pe": 1},
{"rota": "Caxias do Sul - Coronel Pilar", "pe": 4},
{"rota": "Caxias do Sul - Farroupilha", "pe": 1},
{"rota": "Caxias do Sul - Flores Da Cunha", "pe": 1},
{"rota": "Caxias do Sul - Garibaldi", "pe": 1},
{"rota": "Caxias do Sul - Monte Belo Do Sul", "pe": 3},
{"rota": "Caxias do Sul - Nova Pádua", "pe": 3},
{"rota": "Caxias do Sul - Nova Roma Do Sul", "pe": 4},
{"rota": "Caxias do Sul - Pinto Bandeira", "pe": 4},
{"rota": "Caxias do Sul - São Marcos", "pe": 1},
{"rota": "Caxias do Sul - São Pedro Da Serra", "pe": 3},
{"rota": "Caxias do Sul - São Vendelino", "pe": 4},
{"rota": "Caxias do Sul - Vale Real", "pe": 4},
{"rota": "Erechim - Aratiba", "pe": 4},
{"rota": "Erechim - Áurea", "pe": 4},
{"rota": "Erechim - Barão De Cotegipe", "pe": 1},
{"rota": "Erechim - Barra Do Rio Azul", "pe": 4},
{"rota": "Erechim - Benjamin Constant Do Sul", "pe": 4},
{"rota": "Erechim - Campinas Do Sul", "pe": 4},
{"rota": "Erechim - Carlos Gomes", "pe": 4},
{"rota": "Erechim - Centenário", "pe": 4},
{"rota": "Erechim - Coxilha", "pe": 4},
{"rota": "Erechim - Cruzaltense", "pe": 4},
{"rota": "Erechim - Entre Rios Do Sul", "pe": 4},
{"rota": "Erechim - Erebango", "pe": 4},
{"rota": "Erechim - Erechim", "pe": 1},
{"rota": "Erechim - Erval Grande", "pe": 4},
{"rota": "Erechim - Estação", "pe": 1},
{"rota": "Erechim - Faxinalzinho", "pe": 4},
{"rota": "Erechim - Floriano Peixoto", "pe": 4},
{"rota": "Erechim - Gaurama", "pe": 4},
{"rota": "Erechim - Getúlio Vargas", "pe": 1},
{"rota": "Erechim - Ipiranga Do Sul", "pe": 4},
{"rota": "Erechim - Itatiba Do Sul", "pe": 4},
{"rota": "Erechim - Jacutinga", "pe": 4},
{"rota": "Erechim - Marcelino Ramos", "pe": 4},
{"rota": "Erechim - Mariano Moro", "pe": 4},
{"rota": "Erechim - Paulo Bento", "pe": 4},
{"rota": "Erechim - Ponte Preta", "pe": 4},
{"rota": "Erechim - Quatro Irmãos", "pe": 4},
{"rota": "Erechim - São Valentim", "pe": 4},
{"rota": "Erechim - Sertão", "pe": 3},
{"rota": "Erechim - Severiano De Almeida", "pe": 4},
{"rota": "Erechim - Três Arroios", "pe": 4},
{"rota": "Erechim - Viadutos", "pe": 4},
{"rota": "Ijuí - Ajuricaba", "pe": 3},
{"rota": "Ijuí - Augusto Pestana", "pe": 3},
{"rota": "Ijuí - Boa Vista Do Cadeado", "pe": 4},
{"rota": "Ijuí - Boa Vista Do Incra", "pe": 4},
{"rota": "Ijuí - Bozano", "pe": 4},
{"rota": "Ijuí - Caibaté", "pe": 3},
{"rota": "Ijuí - Catuípe", "pe": 3},
{"rota": "Ijuí - Cerro Largo", "pe": 2},
{"rota": "Ijuí - Condor", "pe": 3},
{"rota": "Ijuí - Coronel Barros", "pe": 2},
{"rota": "Ijuí - Cruz Alta", "pe": 2},
{"rota": "Ijuí - Dezesseis De Novembro", "pe": 4},
{"rota": "Ijuí - Entre-Ijuís", "pe": 2},
{"rota": "Ijuí - Eugênio De Castro", "pe": 4},
{"rota": "Ijuí - Garruchos", "pe": 4},
{"rota": "Ijuí - Guarani Das Missões", "pe": 3},
{"rota": "Ijuí - Ijuí", "pe": 1},
{"rota": "Ijuí - Jóia", "pe": 3},
{"rota": "Ijuí - Mato Queimado", "pe": 4},
{"rota": "Ijuí - Nova Ramada", "pe": 4},
{"rota": "Ijuí - Pejuçara", "pe": 3},
{"rota": "Ijuí - Rolador", "pe": 4},
{"rota": "Ijuí - Roque Gonzales", "pe": 3},
{"rota": "Ijuí - Saldanha Marinho", "pe": 4},
{"rota": "Ijuí - Salvador Das Missões", "pe": 3},
{"rota": "Ijuí - Santa Bárbara Do Sul", "pe": 3},
{"rota": "Ijuí - Santo Ângelo", "pe": 1},
{"rota": "Ijuí - Santo Antônio Das Missões", "pe": 3},
{"rota": "Ijuí - São Luiz Gonzaga", "pe": 2},
{"rota": "Ijuí - São Miguel Das Missões", "pe": 3},
{"rota": "Ijuí - São Nicolau", "pe": 4},
{"rota": "Ijuí - São Pedro Do Butiá", "pe": 3},
{"rota": "Ijuí - Sete De Setembro", "pe": 3},
{"rota": "Ijuí - Vitória Das Missões", "pe": 3},
{"rota": "Lajeado - Anta Gorda", "pe": 3},
{"rota": "Lajeado - Arroio Do Meio", "pe": 1},
{"rota": "Lajeado - Arvorezinha", "pe": 3},
{"rota": "Lajeado - Barros Cassal", "pe": 4},
{"rota": "Lajeado - Boa Vista Do Sul", "pe": 4},
{"rota": "Lajeado - Bom Retiro Do Sul", "pe": 2},
{"rota": "Lajeado - Boqueirão Do Leão", "pe": 4},
{"rota": "Lajeado - Canudos Do Vale", "pe": 4},
{"rota": "Lajeado - Capitão", "pe": 3},
{"rota": "Lajeado - Colinas", "pe": 2},
{"rota": "Lajeado - Coqueiro Baixo", "pe": 4},
{"rota": "Lajeado - Cruzeiro Do Sul", "pe": 1},
{"rota": "Lajeado - Doutor Ricardo", "pe": 2},
{"rota": "Lajeado - Encantado", "pe": 1},
{"rota": "Lajeado - Estrela", "pe": 1},
{"rota": "Lajeado - Fazenda Vilanova", "pe": 2},
{"rota": "Lajeado - Fontoura Xavier", "pe": 3},
{"rota": "Lajeado - Forquetinha", "pe": 2},
{"rota": "Lajeado - Gramado Xavier", "pe": 4},
{"rota": "Lajeado - Ilópolis", "pe": 3},
{"rota": "Lajeado - Imigrante", "pe": 2},
{"rota": "Lajeado - Lajeado", "pe": 1},
{"rota": "Lajeado - Marques De Souza", "pe": 3},
{"rota": "Lajeado - Mato Leitão", "pe": 1},
{"rota": "Lajeado - Muçum", "pe": 1},
{"rota": "Lajeado - Nova Bréscia", "pe": 4},
{"rota": "Lajeado - Paverama", "pe": 3},
{"rota": "Lajeado - Poço Das Antas", "pe": 3},
{"rota": "Lajeado - Pouso Novo", "pe": 3},
{"rota": "Lajeado - Progresso", "pe": 2},
{"rota": "Lajeado - Putinga", "pe": 3},
{"rota": "Lajeado - Relvado", "pe": 3},
{"rota": "Lajeado - Roca Sales", "pe": 1},
{"rota": "Lajeado - Santa Clara Do Sul", "pe": 1},
{"rota": "Lajeado - São José Do Herval", "pe": 3},
{"rota": "Lajeado - Sério", "pe": 5},
{"rota": "Lajeado - Tabaí", "pe": 3},
{"rota": "Lajeado - Taquari", "pe": 3},
{"rota": "Lajeado - Teutônia", "pe": 1},
{"rota": "Lajeado - Travesseiro", "pe": 3},
{"rota": "Lajeado - Vespasiano Corrêa", "pe": 4},
{"rota": "Lajeado - Westfália", "pe": 1},
{"rota": "Panambi - Panambi", "pe": 2},
{"rota": "Passo Fundo - Água Santa", "pe": 4},
{"rota": "Passo Fundo - Almirante Tamandaré Do Sul", "pe": 4},
{"rota": "Passo Fundo - Alpestre", "pe": 3},
{"rota": "Passo Fundo - Alto Alegre", "pe": 4},
{"rota": "Passo Fundo - Ametista Do Sul", "pe": 3},
{"rota": "Passo Fundo - Barra Funda", "pe": 2},
{"rota": "Passo Fundo - Barracão", "pe": 4},
{"rota": "Passo Fundo - Boa Vista Das Missões", "pe": 3},
{"rota": "Passo Fundo - Cacique Doble", "pe": 4},
{"rota": "Passo Fundo - Caiçara", "pe": 3},
{"rota": "Passo Fundo - Campos Borges", "pe": 4},
{"rota": "Passo Fundo - Carazinho", "pe": 3},
{"rota": "Passo Fundo - Cerro Grande", "pe": 4},
{"rota": "Passo Fundo - Chapada", "pe": 2},
{"rota": "Passo Fundo - Charrua", "pe": 4},
{"rota": "Passo Fundo - Colorado", "pe": 4},
{"rota": "Passo Fundo - Constantina", "pe": 3},
{"rota": "Passo Fundo - Coqueiros Do Sul", "pe": 4},
{"rota": "Passo Fundo - Cristal Do Sul", "pe": 3},
{"rota": "Passo Fundo - Engenho Velho", "pe": 4},
{"rota": "Passo Fundo - Ernestina", "pe": 3},
{"rota": "Passo Fundo - Erval Seco", "pe": 3},
{"rota": "Passo Fundo - Espumoso", "pe": 3},
{"rota": "Passo Fundo - Fortaleza Dos Valos", "pe": 4},
{"rota": "Passo Fundo - Frederico Westphalen", "pe": 3},
{"rota": "Passo Fundo - Gramado Dos Loureiros", "pe": 4},
{"rota": "Passo Fundo - Ibiaçá", "pe": 4},
{"rota": "Passo Fundo - Ibirapuitã", "pe": 4},
{"rota": "Passo Fundo - Ibirubá", "pe": 3},
{"rota": "Passo Fundo - Iraí", "pe": 3},
{"rota": "Passo Fundo - Jaboticaba", "pe": 4},
{"rota": "Passo Fundo - Jacuizinho", "pe": 4},
{"rota": "Passo Fundo - Lagoa Dos Três Cantos", "pe": 4},
{"rota": "Passo Fundo - Lajeado Do Bugre", "pe": 4},
{"rota": "Passo Fundo - Liberato Salzano", "pe": 3},
{"rota": "Passo Fundo - Machadinho", "pe": 5},
{"rota": "Passo Fundo - Mato Castelhano", "pe": 4},
{"rota": "Passo Fundo - Maximiliano De Almeida", "pe": 4},
{"rota": "Passo Fundo - Mormaço", "pe": 4},
{"rota": "Passo Fundo - Não-Me-Toque", "pe": 3},
{"rota": "Passo Fundo - Nicolau Vergueiro", "pe": 4},
{"rota": "Passo Fundo - Nonoai", "pe": 4},
{"rota": "Passo Fundo - Nova Boa Vista", "pe": 4},
{"rota": "Passo Fundo - Novo Barreiro", "pe": 2},
{"rota": "Passo Fundo - Novo Tiradentes", "pe": 4},
{"rota": "Passo Fundo - Novo Xingu", "pe": 4},
{"rota": "Passo Fundo - Paim Filho", "pe": 4},
{"rota": "Passo Fundo - Palmeira Das Missões", "pe": 4},
{"rota": "Passo Fundo - Palmitinho", "pe": 4},
{"rota": "Passo Fundo - Passo Fundo", "pe": 1},
{"rota": "Passo Fundo - Pinhal", "pe": 4},
{"rota": "Passo Fundo - Pinheirinho Do Vale", "pe": 4},
{"rota": "Passo Fundo - Planalto", "pe": 4},
{"rota": "Passo Fundo - Pontão", "pe": 4},
{"rota": "Passo Fundo - Quinze De Novembro", "pe": 4},
{"rota": "Passo Fundo - Rio Dos Índios", "pe": 4},
{"rota": "Passo Fundo - Rodeio Bonito", "pe": 4},
{"rota": "Passo Fundo - Ronda Alta", "pe": 4},
{"rota": "Passo Fundo - Rondinha", "pe": 4},
{"rota": "Passo Fundo - Sagrada Família", "pe": 4},
{"rota": "Passo Fundo - Salto Do Jacuí", "pe": 4},
{"rota": "Passo Fundo - Sananduva", "pe": 4},
{"rota": "Passo Fundo - Santa Cecília Do Sul", "pe": 4},
{"rota": "Passo Fundo - Santo Antônio Do Planalto", "pe": 4},
{"rota": "Passo Fundo - Santo Expedito Do Sul", "pe": 4},
{"rota": "Passo Fundo - São João Da Urtiga", "pe": 4},
{"rota": "Passo Fundo - São José Das Missões", "pe": 4},
{"rota": "Passo Fundo - São José Do Ouro", "pe": 4},
{"rota": "Passo Fundo - Sarandi", "pe": 3},
{"rota": "Passo Fundo - Seberi", "pe": 4},
{"rota": "Passo Fundo - Selbach", "pe": 4},
{"rota": "Passo Fundo - Soledade", "pe": 3},
{"rota": "Passo Fundo - Tapejara", "pe": 4},
{"rota": "Passo Fundo - Tapera", "pe": 3},
{"rota": "Passo Fundo - Taquaruçu Do Sul", "pe": 4},
{"rota": "Passo Fundo - Tio Hugo", "pe": 3},
{"rota": "Passo Fundo - Três Palmeiras", "pe": 4},
{"rota": "Passo Fundo - Trindade Do Sul", "pe": 4},
{"rota": "Passo Fundo - Tupanci Do Sul", "pe": 4},
{"rota": "Passo Fundo - Vicente Dutra", "pe": 4},
{"rota": "Passo Fundo - Victor Graeff", "pe": 3},
{"rota": "Passo Fundo - Vila Lângaro", "pe": 4},
{"rota": "Passo Fundo - Vista Alegre", "pe": 4},
{"rota": "Pelotas - Arroio Do Padre", "pe": 4},
{"rota": "Pelotas - Arroio Grande", "pe": 3},
{"rota": "Pelotas - Candiota", "pe": 2},
{"rota": "Pelotas - Canguçu", "pe": 3},
{"rota": "Pelotas - Capão Do Leão", "pe": 2},
{"rota": "Pelotas - Cerrito", "pe": 3},
{"rota": "Pelotas - Chuí", "pe": 3},
{"rota": "Pelotas - Herval", "pe": 4},
{"rota": "Pelotas - Jaguarão", "pe": 3},
{"rota": "Pelotas - Morro Redondo", "pe": 3},
{"rota": "Pelotas - Pedras Altas", "pe": 3},
{"rota": "Pelotas - Pedro Osório", "pe": 3},
{"rota": "Pelotas - Pelotas", "pe": 1},
{"rota": "Pelotas - Pinheiro Machado", "pe": 3},
{"rota": "Pelotas - Piratini", "pe": 3},
{"rota": "Pelotas - Santa Vitória Do Palmar", "pe": 3},
{"rota": "Pelotas - São Lourenço Do Sul", "pe": 3},
{"rota": "Pelotas - Turuçu", "pe": 3},
{"rota": "Rio Grande - Rio Grande", "pe": 1},
{"rota": "Santa Cruz do Sul - Arroio Do Tigre", "pe": 3},
{"rota": "Santa Cruz do Sul - Cachoeira Do Sul", "pe": 3},
{"rota": "Santa Cruz do Sul - Candelária", "pe": 3},
{"rota": "Santa Cruz do Sul - Cerro Branco", "pe": 3},
{"rota": "Santa Cruz do Sul - Encruzilhada Do Sul", "pe": 4},
{"rota": "Santa Cruz do Sul - Estrela Velha", "pe": 4},
{"rota": "Santa Cruz do Sul - Herveiras", "pe": 4},
{"rota": "Santa Cruz do Sul - Ibarama", "pe": 4},
{"rota": "Santa Cruz do Sul - Lagoa Bonita Do Sul", "pe": 4},
{"rota": "Santa Cruz do Sul - Lagoão", "pe": 4},
{"rota": "Santa Cruz do Sul - Novo Cabrais", "pe": 3},
{"rota": "Santa Cruz do Sul - Pantano Grande", "pe": 4},
{"rota": "Santa Cruz do Sul - Passa Sete", "pe": 4},
{"rota": "Santa Cruz do Sul - Passo Do Sobrado", "pe": 3},
{"rota": "Santa Cruz do Sul - Rio Pardo", "pe": 3},
{"rota": "Santa Cruz do Sul - Santa Cruz Do Sul", "pe": 1},
{"rota": "Santa Cruz do Sul - Segredo", "pe": 4},
{"rota": "Santa Cruz do Sul - Sinimbu", "pe": 3},
{"rota": "Santa Cruz do Sul - Sobradinho", "pe": 3},
{"rota": "Santa Cruz do Sul - Tunas", "pe": 4},
{"rota": "Santa Cruz do Sul - Vale Do Sol", "pe": 4},
{"rota": "Santa Cruz do Sul - Vale Verde", "pe": 4},
{"rota": "Santa Cruz do Sul - Venâncio Aires", "pe": 2},
{"rota": "Santa Cruz do Sul - Vera Cruz", "pe": 1},
{"rota": "Santa Maria - Aceguá", "pe": 3},
{"rota": "Santa Maria - Agudo", "pe": 2},
{"rota": "Santa Maria - Bagé", "pe": 3},
{"rota": "Santa Maria - Caçapava Do Sul", "pe": 3},
{"rota": "Santa Maria - Dilermando De Aguiar", "pe": 4},
{"rota": "Santa Maria - Dom Pedrito", "pe": 3},
{"rota": "Santa Maria - Dona Francisca", "pe": 2},
{"rota": "Santa Maria - Faxinal Do Soturno", "pe": 2},
{"rota": "Santa Maria - Formigueiro", "pe": 4},
{"rota": "Santa Maria - Hulha Negra", "pe": 4},
{"rota": "Santa Maria - Itaara", "pe": 4},
{"rota": "Santa Maria - Ivorá", "pe": 4},
{"rota": "Santa Maria - Jari", "pe": 4},
{"rota": "Santa Maria - Júlio De Castilhos", "pe": 3},
{"rota": "Santa Maria - Lavras Do Sul", "pe": 4},
{"rota": "Santa Maria - Mata", "pe": 4},
{"rota": "Santa Maria - Nova Palma", "pe": 2},
{"rota": "Santa Maria - Paraíso Do Sul", "pe": 4},
{"rota": "Santa Maria - Pinhal Grande", "pe": 4},
{"rota": "Santa Maria - Quevedos", "pe": 4},
{"rota": "Santa Maria - Restinga Sêca", "pe": 4},
{"rota": "Santa Maria - Santa Maria", "pe": 1},
{"rota": "Santa Maria - Santana Da Boa Vista", "pe": 4},
{"rota": "Santa Maria - São Francisco De Assis", "pe": 4},
{"rota": "Santa Maria - São João Do Polêsine", "pe": 2},
{"rota": "Santa Maria - São Martinho Da Serra", "pe": 4},
{"rota": "Santa Maria - São Pedro Do Sul", "pe": 1},
{"rota": "Santa Maria - São Sepé", "pe": 3},
{"rota": "Santa Maria - Silveira Martins", "pe": 4},
{"rota": "Santa Maria - Toropi", "pe": 4},
{"rota": "Santa Maria - Tupanciretã", "pe": 3},
{"rota": "Santa Rosa - Alecrim", "pe": 3},
{"rota": "Santa Rosa - Alegria", "pe": 4},
{"rota": "Santa Rosa - Barra Do Guarita", "pe": 4},
{"rota": "Santa Rosa - Boa Vista Do Buricá", "pe": 2},
{"rota": "Santa Rosa - Bom Progresso", "pe": 2},
{"rota": "Santa Rosa - Braga", "pe": 4},
{"rota": "Santa Rosa - Campina Das Missões", "pe": 3},
{"rota": "Santa Rosa - Campo Novo", "pe": 2},
{"rota": "Santa Rosa - Cândido Godói", "pe": 3},
{"rota": "Santa Rosa - Chiapetta", "pe": 4},
{"rota": "Santa Rosa - Coronel Bicaco", "pe": 4},
{"rota": "Santa Rosa - Crissiumal", "pe": 2},
{"rota": "Santa Rosa - Doutor Maurício Cardoso", "pe": 4},
{"rota": "Santa Rosa - Esperança Do Sul", "pe": 4},
{"rota": "Santa Rosa - Giruá", "pe": 1},
{"rota": "Santa Rosa - Horizontina", "pe": 1},
{"rota": "Santa Rosa - Humaitá", "pe": 2},
{"rota": "Santa Rosa - Independência", "pe": 1},
{"rota": "Santa Rosa - Inhacorá", "pe": 4},
{"rota": "Santa Rosa - Miraguaí", "pe": 3},
{"rota": "Santa Rosa - Nova Candelária", "pe": 2},
{"rota": "Santa Rosa - Novo Machado", "pe": 4},
{"rota": "Santa Rosa - Pirapó", "pe": 4},
{"rota": "Santa Rosa - Porto Lucena", "pe": 3},
{"rota": "Santa Rosa - Porto Mauá", "pe": 4},
{"rota": "Santa Rosa - Porto Vera Cruz", "pe": 4},
{"rota": "Santa Rosa - Porto Xavier", "pe": 3},
{"rota": "Santa Rosa - Santa Rosa", "pe": 1},
{"rota": "Santa Rosa - Santo Augusto", "pe": 2},
{"rota": "Santa Rosa - Santo Cristo", "pe": 1},
{"rota": "Santa Rosa - São José Do Inhacorá", "pe": 2},
{"rota": "Santa Rosa - São Martinho", "pe": 2},
{"rota": "Santa Rosa - São Paulo Das Missões", "pe": 4},
{"rota": "Santa Rosa - São Valério Do Sul", "pe": 4},
{"rota": "Santa Rosa - Sede Nova", "pe": 4},
{"rota": "Santa Rosa - Senador Salgado Filho", "pe": 4},
{"rota": "Santa Rosa - Tenente Portela", "pe": 4},
{"rota": "Santa Rosa - Tiradentes Do Sul", "pe": 4},
{"rota": "Santa Rosa - Três De Maio", "pe": 2},
{"rota": "Santa Rosa - Três Passos", "pe": 2},
{"rota": "Santa Rosa - Tucunduva", "pe": 2},
{"rota": "Santa Rosa - Tuparendi", "pe": 2},
{"rota": "Santa Rosa - Ubiretama", "pe": 4},
{"rota": "Santa Rosa - Vista Gaúcha", "pe": 4},
{"rota": "Sant'ana do Livramento - Sant'Ana Do Livramento", "pe": 1},
{"rota": "Santiago - Bossoroca", "pe": 4},
{"rota": "Santiago - Cacequi", "pe": 3},
{"rota": "Santiago - Capão Do Cipó", "pe": 4},
{"rota": "Santiago - Itacurubi", "pe": 4},
{"rota": "Santiago - Jaguari", "pe": 3},
{"rota": "Santiago - Maçambará", "pe": 4},
{"rota": "Santiago - Nova Esperança Do Sul", "pe": 3},
{"rota": "Santiago - Santiago", "pe": 1},
{"rota": "Santiago - São Vicente Do Sul", "pe": 3},
{"rota": "Santiago - Unistalda", "pe": 4},
{"rota": "Santo Antônio da Patrulha - Arroio Do Sal", "pe": 3},
{"rota": "Santo Antônio da Patrulha - Balneário Pinhal", "pe": 3},
{"rota": "Santo Antônio da Patrulha - Capão Da Canoa", "pe": 1},
{"rota": "Santo Antônio da Patrulha - Capivari Do Sul", "pe": 3},
{"rota": "Santo Antônio da Patrulha - Caraá", "pe": 4},
{"rota": "Santo Antônio da Patrulha - Cidreira", "pe": 3},
{"rota": "Santo Antônio da Patrulha - Dom Pedro De Alcântara", "pe": 3},
{"rota": "Santo Antônio da Patrulha - Glorinha", "pe": 3},
{"rota": "Santo Antônio da Patrulha - Imbé", "pe": 1},
{"rota": "Santo Antônio da Patrulha - Itati", "pe": 3},
{"rota": "Santo Antônio da Patrulha - Mampituba", "pe": 4},
{"rota": "Santo Antônio da Patrulha - Maquiné", "pe": 3},
{"rota": "Santo Antônio da Patrulha - Morrinhos Do Sul", "pe": 3},
{"rota": "Santo Antônio da Patrulha - Mostardas", "pe": 3},
{"rota": "Santo Antônio da Patrulha - Osório", "pe": 1},
{"rota": "Santo Antônio da Patrulha - Palmares Do Sul", "pe": 3},
{"rota": "Santo Antônio da Patrulha - Santo Antônio Da Patrulha", "pe": 2},
{"rota": "Santo Antônio da Patrulha - Tavares", "pe": 3},
{"rota": "Santo Antônio da Patrulha - Terra De Areia", "pe": 3},
{"rota": "Santo Antônio da Patrulha - Torres", "pe": 2},
{"rota": "Santo Antônio da Patrulha - Tramandaí", "pe": 1},
{"rota": "Santo Antônio da Patrulha - Três Cachoeiras", "pe": 3},
{"rota": "Santo Antônio da Patrulha - Três Forquilhas", "pe": 3},
{"rota": "Santo Antônio da Patrulha - Xangri-Lá", "pe": 1},
{"rota": "São Gabriel - Rosário Do Sul", "pe": 2},
{"rota": "São Gabriel - Santa Margarida Do Sul", "pe": 4},
{"rota": "São Gabriel - São Gabriel", "pe": 1},
{"rota": "São Gabriel - Vila Nova Do Sul", "pe": 4},
{"rota": "Serafina Corrêa - André Da Rocha", "pe": 4},
{"rota": "Serafina Corrêa - Camargo", "pe": 4},
{"rota": "Serafina Corrêa - Casca", "pe": 2},
{"rota": "Serafina Corrêa - Caseiros", "pe": 4},
{"rota": "Serafina Corrêa - Ciríaco", "pe": 3},
{"rota": "Serafina Corrêa - Cotiporã", "pe": 3},
{"rota": "Serafina Corrêa - David Canabarro", "pe": 3},
{"rota": "Serafina Corrêa - Dois Lajeados", "pe": 4},
{"rota": "Serafina Corrêa - Fagundes Varela", "pe": 4},
{"rota": "Serafina Corrêa - Gentil", "pe": 4},
{"rota": "Serafina Corrêa - Guabiju", "pe": 3},
{"rota": "Serafina Corrêa - Guaporé", "pe": 2},
{"rota": "Serafina Corrêa - Ibiraiaras", "pe": 4},
{"rota": "Serafina Corrêa - Marau", "pe": 4},
{"rota": "Serafina Corrêa - Montauri", "pe": 4},
{"rota": "Serafina Corrêa - Muliterno", "pe": 4},
{"rota": "Serafina Corrêa - Nova Alvorada", "pe": 4},
{"rota": "Serafina Corrêa - Nova Araçá", "pe": 2},
{"rota": "Serafina Corrêa - Nova Bassano", "pe": 3},
{"rota": "Serafina Corrêa - Nova Prata", "pe": 2},
{"rota": "Serafina Corrêa - Paraí", "pe": 2},
{"rota": "Serafina Corrêa - Protásio Alves", "pe": 4},
{"rota": "Serafina Corrêa - Santo Antônio Do Palma", "pe": 4},
{"rota": "Serafina Corrêa - São Domingos Do Sul", "pe": 3},
{"rota": "Serafina Corrêa - São Jorge", "pe": 3},
{"rota": "Serafina Corrêa - São Valentim Do Sul", "pe": 4},
{"rota": "Serafina Corrêa - Serafina Corrêa", "pe": 2},
{"rota": "Serafina Corrêa - União Da Serra", "pe": 3},
{"rota": "Serafina Corrêa - Vanini", "pe": 3},
{"rota": "Serafina Corrêa - Veranópolis", "pe": 1},
{"rota": "Serafina Corrêa - Vila Flores", "pe": 1},
{"rota": "Serafina Corrêa - Vila Maria", "pe": 4},
{"rota": "Serafina Corrêa - Vista Alegre Do Prata", "pe": 4},
{"rota": "Três Coroas - Nova Hartz", "pe": 3},
{"rota": "Três Coroas - Três Coroas", "pe": 1},
{"rota": "Uruguaiana - Barra Do Quaraí", "pe": 3},
{"rota": "Uruguaiana - Itaqui", "pe": 2},
{"rota": "Uruguaiana - São Borja", "pe": 2},
{"rota": "Uruguaiana - Uruguaiana", "pe": 1},
{"rota": "Vacaria - Antônio Prado", "pe": 3},
{"rota": "Vacaria - Campestre Da Serra", "pe": 4},
{"rota": "Vacaria - Capão Bonito Do Sul", "pe": 4},
{"rota": "Vacaria - Esmeralda", "pe": 4},
{"rota": "Vacaria - Ipê", "pe": 1},
{"rota": "Vacaria - Lagoa Vermelha", "pe": 3},
{"rota": "Vacaria - Monte Alegre Dos Campos", "pe": 4},
{"rota": "Vacaria - Muitos Capões", "pe": 3},
{"rota": "Vacaria - Pinhal Da Serra", "pe": 4},
{"rota": "Vacaria - Vacaria", "pe": 1},
{"rota": "Araquari - Araquari", "pe": 1},
{"rota": "Araquari - Balneário Barra Do Sul", "pe": 2},
{"rota": "Araquari - Balneário Camboriú", "pe": 1},
{"rota": "Araquari - Balneário Piçarras", "pe": 1},
{"rota": "Araquari - Barra Velha", "pe": 2},
{"rota": "Araquari - Bombinhas", "pe": 3},
{"rota": "Araquari - Botuverá", "pe": 3},
{"rota": "Araquari - Brusque", "pe": 3},
{"rota": "Araquari - Camboriú", "pe": 2},
{"rota": "Araquari - Canelinha", "pe": 3},
{"rota": "Araquari - Garuva", "pe": 1},
{"rota": "Araquari - Guabiruba", "pe": 3},
{"rota": "Araquari - Icaraíma", "pe": 4},
{"rota": "Araquari - Ilhota", "pe": 1},
{"rota": "Araquari - Itajaí", "pe": 2},
{"rota": "Araquari - Itapema", "pe": 2},
{"rota": "Araquari - Itapoá", "pe": 3},
{"rota": "Araquari - Joinville", "pe": 1},
{"rota": "Araquari - Navegantes", "pe": 1},
{"rota": "Araquari - Nova Trento", "pe": 3},
{"rota": "Araquari - Penha", "pe": 1},
{"rota": "Araquari - Porto Belo", "pe": 2},
{"rota": "Araquari - São Francisco Do Sul", "pe": 2},
{"rota": "Araquari - São João Batista", "pe": 3},
{"rota": "Araquari - São João Do Itaperiú", "pe": 3},
{"rota": "Araquari - Tijucas", "pe": 2},
{"rota": "Biguaçu - Águas Mornas", "pe": 3},
{"rota": "Biguaçu - Angelina", "pe": 3},
{"rota": "Biguaçu - Anitápolis", "pe": 3},
{"rota": "Biguaçu - Antônio Carlos", "pe": 2},
{"rota": "Biguaçu - Biguaçu", "pe": 1},
{"rota": "Biguaçu - Florianópolis", "pe": 1},
{"rota": "Biguaçu - Governador Celso Ramos", "pe": 2},
{"rota": "Biguaçu - Major Gercino", "pe": 3},
{"rota": "Biguaçu - Palhoça", "pe": 1},
{"rota": "Biguaçu - Paulo Lopes", "pe": 3},
{"rota": "Biguaçu - Rancho Queimado", "pe": 3},
{"rota": "Biguaçu - Santo Amaro Da Imperatriz", "pe": 2},
{"rota": "Biguaçu - São Bonifácio", "pe": 3},
{"rota": "Biguaçu - São José", "pe": 1},
{"rota": "Biguaçu - São Pedro De Alcântara", "pe": 3},
{"rota": "Blumenau - Ascurra", "pe": 3},
{"rota": "Blumenau - Benedito Novo", "pe": 3},
{"rota": "Blumenau - Blumenau", "pe": 1},
{"rota": "Blumenau - Doutor Pedrinho", "pe": 3},
{"rota": "Blumenau - Gaspar", "pe": 1},
{"rota": "Blumenau - Indaial", "pe": 1},
{"rota": "Blumenau - Pomerode", "pe": 2},
{"rota": "Blumenau - Rio Dos Cedros", "pe": 1},
{"rota": "Blumenau - Rodeio", "pe": 3},
{"rota": "Blumenau - Timbó", "pe": 1},
{"rota": "Chapecó - Abelardo Luz", "pe": 3},
{"rota": "Chapecó - Águas De Chapecó", "pe": 3},
{"rota": "Chapecó - Águas Frias", "pe": 3},
{"rota": "Chapecó - Anchieta", "pe": 3},
{"rota": "Chapecó - Arvoredo", "pe": 3},
{"rota": "Chapecó - Bandeirante", "pe": 3},
{"rota": "Chapecó - Barra Bonita", "pe": 3},
{"rota": "Chapecó - Belmonte", "pe": 3},
{"rota": "Chapecó - Bom Jesus", "pe": 3},
{"rota": "Chapecó - Bom Jesus Do Oeste", "pe": 3},
{"rota": "Chapecó - Caibi", "pe": 3},
{"rota": "Chapecó - Campo Erê", "pe": 3},
{"rota": "Chapecó - Caxambu Do Sul", "pe": 3},
{"rota": "Chapecó - Chapecó", "pe": 1},
{"rota": "Chapecó - Cordilheira Alta", "pe": 1},
{"rota": "Chapecó - Coronel Freitas", "pe": 3},
{"rota": "Chapecó - Coronel Martins", "pe": 3},
{"rota": "Chapecó - Cunha Porã", "pe": 2},
{"rota": "Chapecó - Cunhataí", "pe": 3},
{"rota": "Chapecó - Descanso", "pe": 3},
{"rota": "Chapecó - Dionísio Cerqueira", "pe": 3},
{"rota": "Chapecó - Faxinal Dos Guedes", "pe": 3},
{"rota": "Chapecó - Flor Do Sertão", "pe": 3},
{"rota": "Chapecó - Formosa Do Sul", "pe": 3},
{"rota": "Chapecó - Galvão", "pe": 3},
{"rota": "Chapecó - Guaraciaba", "pe": 2},
{"rota": "Chapecó - Guarujá Do Sul", "pe": 3},
{"rota": "Chapecó - Guatambú", "pe": 3},
{"rota": "Chapecó - Iporã Do Oeste", "pe": 3},
{"rota": "Chapecó - Ipuaçu", "pe": 3},
{"rota": "Chapecó - Iraceminha", "pe": 3},
{"rota": "Chapecó - Irati", "pe": 3},
{"rota": "Chapecó - Itá", "pe": 3},
{"rota": "Chapecó - Itapiranga", "pe": 3},
{"rota": "Chapecó - Jardinópolis", "pe": 3},
{"rota": "Chapecó - Jupiá", "pe": 3},
{"rota": "Chapecó - Lajeado Grande", "pe": 3},
{"rota": "Chapecó - Maravilha", "pe": 2},
{"rota": "Chapecó - Marema", "pe": 3},
{"rota": "Chapecó - Modelo", "pe": 3},
{"rota": "Chapecó - Mondaí", "pe": 3},
{"rota": "Chapecó - Nova Erechim", "pe": 2},
{"rota": "Chapecó - Nova Itaberaba", "pe": 3},
{"rota": "Chapecó - Novo Horizonte", "pe": 3},
{"rota": "Chapecó - Ouro Verde", "pe": 3},
{"rota": "Chapecó - Paial", "pe": 3},
{"rota": "Chapecó - Palma Sola", "pe": 3},
{"rota": "Chapecó - Palmitos", "pe": 3},
{"rota": "Chapecó - Paraíso", "pe": 3},
{"rota": "Chapecó - Passos Maia", "pe": 3},
{"rota": "Chapecó - Pinhalzinho", "pe": 2},
{"rota": "Chapecó - Planalto Alegre", "pe": 3},
{"rota": "Chapecó - Ponte Serrada", "pe": 3},
{"rota": "Chapecó - Princesa", "pe": 3},
{"rota": "Chapecó - Quilombo", "pe": 3},
{"rota": "Chapecó - Riqueza", "pe": 3},
{"rota": "Chapecó - Romelândia", "pe": 3},
{"rota": "Chapecó - Saltinho", "pe": 3},
{"rota": "Chapecó - Santa Helena", "pe": 3},
{"rota": "Chapecó - Santa Terezinha Do Progresso", "pe": 3},
{"rota": "Chapecó - Santiago Do Sul", "pe": 3},
{"rota": "Chapecó - São Bernardino", "pe": 3},
{"rota": "Chapecó - São Carlos", "pe": 3},
{"rota": "Chapecó - São Domingos", "pe": 3},
{"rota": "Chapecó - São João Do Oeste", "pe": 3},
{"rota": "Chapecó - São José Do Cedro", "pe": 2},
{"rota": "Chapecó - São Lourenço Do Oeste", "pe": 3},
{"rota": "Chapecó - São Miguel Da Boa Vista", "pe": 3},
{"rota": "Chapecó - São Miguel Do Oeste", "pe": 2},
{"rota": "Chapecó - Saudades", "pe": 2},
{"rota": "Chapecó - Seara", "pe": 3},
{"rota": "Chapecó - Serra Alta", "pe": 3},
{"rota": "Chapecó - Sul Brasil", "pe": 3},
{"rota": "Chapecó - Tigrinhos", "pe": 3},
{"rota": "Chapecó - Tunápolis", "pe": 3},
{"rota": "Chapecó - União Do Oeste", "pe": 3},
{"rota": "Chapecó - Vargeão", "pe": 3},
{"rota": "Chapecó - Xanxerê", "pe": 2},
{"rota": "Chapecó - Xavantina", "pe": 3},
{"rota": "Chapecó - Xaxim", "pe": 2},
{"rota": "Criciúma - Araranguá", "pe": 3},
{"rota": "Criciúma - Balneário Arroio Do Silva", "pe": 3},
{"rota": "Criciúma - Balneário Gaivota", "pe": 3},
{"rota": "Criciúma - Balneário Rincão", "pe": 2},
{"rota": "Criciúma - Cocal Do Sul", "pe": 2},
{"rota": "Criciúma - Criciúma", "pe": 1},
{"rota": "Criciúma - Ermo", "pe": 3},
{"rota": "Criciúma - Forquilhinha", "pe": 1},
{"rota": "Criciúma - Içara", "pe": 1},
{"rota": "Criciúma - Jacinto Machado", "pe": 3},
{"rota": "Criciúma - Lauro Müller", "pe": 3},
{"rota": "Criciúma - Maracajá", "pe": 1},
{"rota": "Criciúma - Meleiro", "pe": 3},
{"rota": "Criciúma - Morro Da Fumaça", "pe": 3},
{"rota": "Criciúma - Morro Grande", "pe": 3},
{"rota": "Criciúma - Nova Veneza", "pe": 1},
{"rota": "Criciúma - Orleans", "pe": 3},
{"rota": "Criciúma - Passo De Torres", "pe": 3},
{"rota": "Criciúma - Praia Grande", "pe": 3},
{"rota": "Criciúma - Santa Rosa Do Sul", "pe": 3},
{"rota": "Criciúma - São João Do Sul", "pe": 3},
{"rota": "Criciúma - Siderópolis", "pe": 2},
{"rota": "Criciúma - Sombrio", "pe": 3},
{"rota": "Criciúma - Timbé Do Sul", "pe": 3},
{"rota": "Criciúma - Treviso", "pe": 3},
{"rota": "Criciúma - Turvo", "pe": 3},
{"rota": "Criciúma - Urussanga", "pe": 3},
{"rota": "Jaraguá do Sul - Corupá", "pe": 2},
{"rota": "Jaraguá do Sul - Guaramirim", "pe": 2},
{"rota": "Jaraguá do Sul - Jaraguá Do Sul", "pe": 1},
{"rota": "Jaraguá do Sul - Massaranduba", "pe": 2},
{"rota": "Jaraguá do Sul - Schroeder", "pe": 2},
{"rota": "Joaçaba - Água Doce", "pe": 1},
{"rota": "Joaçaba - Alto Bela Vista", "pe": 3},
{"rota": "Joaçaba - Arabutã", "pe": 3},
{"rota": "Joaçaba - Arroio Trinta", "pe": 1},
{"rota": "Joaçaba - Caçador", "pe": 1},
{"rota": "Joaçaba - Calmon", "pe": 3},
{"rota": "Joaçaba - Campos Novos", "pe": 1},
{"rota": "Joaçaba - Capinzal", "pe": 1},
{"rota": "Joaçaba - Catanduvas", "pe": 1},
{"rota": "Joaçaba - Concórdia", "pe": 1},
{"rota": "Joaçaba - Erval Velho", "pe": 1},
{"rota": "Joaçaba - Fraiburgo", "pe": 1},
{"rota": "Joaçaba - Herval D'Oeste", "pe": 1},
{"rota": "Joaçaba - Ibicaré", "pe": 1},
{"rota": "Joaçaba - Iomerê", "pe": 1},
{"rota": "Joaçaba - Ipira", "pe": 3},
{"rota": "Joaçaba - Ipumirim", "pe": 3},
{"rota": "Joaçaba - Irani", "pe": 3},
{"rota": "Joaçaba - Jaborá", "pe": 3},
{"rota": "Joaçaba - Joaçaba", "pe": 1},
{"rota": "Joaçaba - Lacerdópolis", "pe": 1},
{"rota": "Joaçaba - Lindóia Do Sul", "pe": 3},
{"rota": "Joaçaba - Luzerna", "pe": 1},
{"rota": "Joaçaba - Macieira", "pe": 3},
{"rota": "Joaçaba - Matos Costa", "pe": 3},
{"rota": "Joaçaba - Monte Carlo", "pe": 3},
{"rota": "Joaçaba - Ouro", "pe": 1},
{"rota": "Joaçaba - Peritiba", "pe": 3},
{"rota": "Joaçaba - Pinheiro Preto", "pe": 2},
{"rota": "Joaçaba - Piratuba", "pe": 3},
{"rota": "Joaçaba - Presidente Castello Branco", "pe": 3},
{"rota": "Joaçaba - Rio Das Antas", "pe": 1},
{"rota": "Joaçaba - Salto Veloso", "pe": 1},
{"rota": "Joaçaba - Tangará", "pe": 1},
{"rota": "Joaçaba - Treze Tílias", "pe": 1},
{"rota": "Joaçaba - Vargem", "pe": 3},
{"rota": "Joaçaba - Vargem Bonita", "pe": 3},
{"rota": "Joaçaba - Videira", "pe": 1},
{"rota": "Joaçaba - Zortéa", "pe": 1},
{"rota": "Lages - Abdon Batista", "pe": 3},
{"rota": "Lages - Alfredo Wagner", "pe": 3},
{"rota": "Lages - Anita Garibaldi", "pe": 3},
{"rota": "Lages - Bocaina Do Sul", "pe": 3},
{"rota": "Lages - Bom Jardim Da Serra", "pe": 3},
{"rota": "Lages - Bom Retiro", "pe": 3},
{"rota": "Lages - Campo Belo Do Sul", "pe": 3},
{"rota": "Lages - Capão Alto", "pe": 3},
{"rota": "Lages - Celso Ramos", "pe": 3},
{"rota": "Lages - Cerro Negro", "pe": 3},
{"rota": "Lages - Correia Pinto", "pe": 2},
{"rota": "Lages - Curitibanos", "pe": 2},
{"rota": "Lages - Frei Rogério", "pe": 3},
{"rota": "Lages - Lages", "pe": 1},
{"rota": "Lages - Lebon Régis", "pe": 3},
{"rota": "Lages - Otacílio Costa", "pe": 2},
{"rota": "Lages - Painel", "pe": 3},
{"rota": "Lages - Palmeira", "pe": 2},
{"rota": "Lages - Ponte Alta", "pe": 2},
{"rota": "Lages - Ponte Alta Do Norte", "pe": 2},
{"rota": "Lages - Rio Rufino", "pe": 3},
{"rota": "Lages - Santa Cecília", "pe": 2},
{"rota": "Lages - São Cristóvão Do Sul", "pe": 2},
{"rota": "Lages - São Joaquim", "pe": 3},
{"rota": "Lages - São José Do Cerrito", "pe": 3},
{"rota": "Lages - Urubici", "pe": 3},
{"rota": "Lages - Urupema", "pe": 3},
{"rota": "Rio do Sul - Agrolândia", "pe": 2},
{"rota": "Rio do Sul - Agronômica", "pe": 1},
{"rota": "Rio do Sul - Atalanta", "pe": 4},
{"rota": "Rio do Sul - Aurora", "pe": 2},
{"rota": "Rio do Sul - Braço Do Trombudo", "pe": 4},
{"rota": "Rio do Sul - Chapadão Do Lageado", "pe": 4},
{"rota": "Rio do Sul - Dona Emma", "pe": 4},
{"rota": "Rio do Sul - Ibirama", "pe": 1},
{"rota": "Rio do Sul - Imbuia", "pe": 3},
{"rota": "Rio do Sul - Ituporanga", "pe": 2},
{"rota": "Rio do Sul - José Boiteux", "pe": 3},
{"rota": "Rio do Sul - Laurentino", "pe": 1},
{"rota": "Rio do Sul - Leoberto Leal", "pe": 4},
{"rota": "Rio do Sul - Lontras", "pe": 2},
{"rota": "Rio do Sul - Mirim Doce", "pe": 4},
{"rota": "Rio do Sul - Petrolândia", "pe": 3},
{"rota": "Rio do Sul - Pouso Redondo", "pe": 2},
{"rota": "Rio do Sul - Presidente Getúlio", "pe": 1},
{"rota": "Rio do Sul - Presidente Nereu", "pe": 4},
{"rota": "Rio do Sul - Rio Do Campo", "pe": 3},
{"rota": "Rio do Sul - Rio Do Oeste", "pe": 2},
{"rota": "Rio do Sul - Rio Do Sul", "pe": 1},
{"rota": "Rio do Sul - Salete", "pe": 2},
{"rota": "Rio do Sul - Santa Terezinha", "pe": 4},
{"rota": "Rio do Sul - Taió", "pe": 2},
{"rota": "Rio do Sul - Trombudo Central", "pe": 2},
{"rota": "Rio do Sul - Vidal Ramos", "pe": 3},
{"rota": "Rio do Sul - Vitor Meireles", "pe": 4},
{"rota": "Rio do Sul - Witmarsum", "pe": 4},
{"rota": "Tubarão - Armazém", "pe": 2},
{"rota": "Tubarão - Braço Do Norte", "pe": 2},
{"rota": "Tubarão - Capivari De Baixo", "pe": 2},
{"rota": "Tubarão - Garopaba", "pe": 2},
{"rota": "Tubarão - Grão Pará", "pe": 3},
{"rota": "Tubarão - Gravatal", "pe": 2},
{"rota": "Tubarão - Imaruí", "pe": 4},
{"rota": "Tubarão - Imbituba", "pe": 2},
{"rota": "Tubarão - Jaguaruna", "pe": 2},
{"rota": "Tubarão - Laguna", "pe": 2},
{"rota": "Tubarão - Pedras Grandes", "pe": 4},
{"rota": "Tubarão - Pescaria Brava", "pe": 4},
{"rota": "Tubarão - Rio Fortuna", "pe": 3},
{"rota": "Tubarão - Sangão", "pe": 2},
{"rota": "Tubarão - Santa Rosa De Lima", "pe": 4},
{"rota": "Tubarão - São Ludgero", "pe": 2},
{"rota": "Tubarão - São Martinho", "pe": 4},
{"rota": "Tubarão - Treze De Maio", "pe": 4},
{"rota": "Tubarão - Tubarão", "pe": 1},
{"rota": "Campinas - Americana", "pe": 1},
{"rota": "Campinas - Artur Nogueira", "pe": 1},
{"rota": "Campinas - Campinas", "pe": 1},
{"rota": "Campinas - Cosmópolis", "pe": 1},
{"rota": "Campinas - Holambra", "pe": 1},
{"rota": "Campinas - Hortolândia", "pe": 1},
{"rota": "Campinas - Indaiatuba", "pe": 1},
{"rota": "Campinas - Itatiba", "pe": 2},
{"rota": "Campinas - Itupeva", "pe": 2},
{"rota": "Campinas - Jaguariúna", "pe": 1},
{"rota": "Campinas - Jarinu", "pe": 1},
{"rota": "Campinas - Jundiaí", "pe": 1},
{"rota": "Campinas - Louveira", "pe": 1},
{"rota": "Campinas - Monte Mor", "pe": 1},
{"rota": "Campinas - Morungaba", "pe": 2},
{"rota": "Campinas - Nova Odessa", "pe": 1},
{"rota": "Campinas - Paulínia", "pe": 1},
{"rota": "Campinas - Pedreira", "pe": 1},
{"rota": "Campinas - Santa Bárbara D'Oeste", "pe": 1},
{"rota": "Campinas - Sumaré", "pe": 1},
{"rota": "Campinas - Valinhos", "pe": 1},
{"rota": "Campinas - Várzea Paulista", "pe": 1},
{"rota": "Campinas - Vinhedo", "pe": 1},
{"rota": "Guarulhos - Arujá", "pe": 2},
{"rota": "Guarulhos - Barueri", "pe": 2},
{"rota": "Guarulhos - Caieiras", "pe": 2},
{"rota": "Guarulhos - Cajamar", "pe": 2},
{"rota": "Guarulhos - Carapicuíba", "pe": 2},
{"rota": "Guarulhos - Diadema", "pe": 2},
{"rota": "Guarulhos - Embu Das Artes", "pe": 2},
{"rota": "Guarulhos - Ferraz De Vasconcelos", "pe": 2},
{"rota": "Guarulhos - Francisco Morato", "pe": 2},
{"rota": "Guarulhos - Franco Da Rocha", "pe": 2},
{"rota": "Guarulhos - Guarulhos", "pe": 2},
{"rota": "Guarulhos - Itapevi", "pe": 2},
{"rota": "Guarulhos - Itaquaquecetuba", "pe": 2},
{"rota": "Guarulhos - Jandira", "pe": 2},
{"rota": "Guarulhos - Mairiporã", "pe": 2},
{"rota": "Guarulhos - Mauá", "pe": 2},
{"rota": "Guarulhos - Mogi Das Cruzes", "pe": 2},
{"rota": "Guarulhos - Osasco", "pe": 2},
{"rota": "Guarulhos - Poá", "pe": 2},
{"rota": "Guarulhos - Ribeirão Pires", "pe": 2},
{"rota": "Guarulhos - Santa Isabel", "pe": 2},
{"rota": "Guarulhos - Santo André", "pe": 2},
{"rota": "Guarulhos - São Bernardo Do Campo", "pe": 2},
{"rota": "Guarulhos - São Caetano Do Sul", "pe": 2},
{"rota": "Guarulhos - São Paulo", "pe": 2},
{"rota": "Guarulhos - Suzano", "pe": 2},
{"rota": "Guarulhos - Taboão Da Serra", "pe": 2}
]
}
